/*
 * WeldWorld data model
 * ------------------------------------------------------------------
 * Edit this file to add or correct content. The markets table,
 * application pages and glossary are all generated from it.
 *
 * Layers (market -> weld chain):
 *   tier -> segment -> app -> process -> automation -> filler -> ndt
 *
 * Links are declared on the node that "owns" them:
 *   segment.tiers      : tier ids the segment belongs to
 *   segment.apps       : [appId, weight 1-5, optional note]
 *                        weight = indicative share of that segment's
 *                        welding workload (analyst judgment, not data)
 *   app.processes / automation / fillers / ndt : what THIS application
 *                        actually uses (specific links). ORDER MATTERS:
 *                        list the primary item first. Mix and matrix
 *                        scores use rank factors 1.0, 0.6, 0.4, 0.3...
 *   process.automation / fillers / ndt : what the process CAN use in
 *                        general (generic links, shown when a process,
 *                        automation, filler or NDT node is selected)
 *
 * All weights, shares and rates are indicative ranges for study and
 * discussion. Validate against ESAB market intelligence before using
 * them in external material.
 */
window.WELD_DATA = {
  meta: {
    version: "1.0",
    updated: "2026-09-28",
    disclaimer:
      "Weights (1–5), shares and deposition rates are indicative analyst estimates for learning and discussion, not market data. Validate before external use.",
  },

  layers: [
    { id: "tier", name: "Industry tier", color: "#AEBBC8" },
    { id: "segment", name: "End segment", color: "#F2A93B" },
    { id: "app", name: "Application", color: "#E8795A" },
    { id: "process", name: "Weld process", color: "#58C4F5" },
    { id: "automation", name: "Automation", color: "#A48CF7" },
    { id: "filler", name: "Filler metal", color: "#D9C46C" },
    { id: "ndt", name: "NDT & QA", color: "#4DD4A6" },
  ],

  nodes: [
    /* ============================ TIERS ============================ */
    {
      id: "tier_light", layer: "tier", name: "Light Industrial",
      sum: "Thin-gauge, high-volume, repeatable parts. Cost per part, cycle time and cosmetics drive decisions.",
      facts: [
        ["Typical thickness", "0.5–6 mm (up to ~1/4 in)"],
        ["Dominant process", "GMAW (short-circuit and pulsed); GTAW for stainless and cosmetic seams"],
        ["Automation", "High robot use in OEMs; cobots growing fastest in job shops"],
        ["Main fillers", "Solid wire, metal-cored wire, TIG rods"],
        ["Quality control", "Visual, in-process arc monitoring, leak tests, cut-and-etch samples"],
        ["Buyer", "OEM manufacturing engineering, job-shop owners, distribution"],
      ],
      insight: "Equipment and wire are often sold together into a robot cell or a cobot package. Uptime, wire packaging (drums) and consistent feedability decide share, and code qualification matters less than in heavy industry.",
    },
    {
      id: "tier_heavy", layer: "tier", name: "Heavy Industrial",
      sum: "Thick sections under code. Deposition rate, first-pass quality and qualified procedures drive decisions.",
      facts: [
        ["Typical thickness", "6–150+ mm"],
        ["Dominant processes", "SAW, FCAW, SMAW, GTAW roots on pipe"],
        ["Automation", "Mechanization: column and boom, tractors, orbital, pipeline systems"],
        ["Main fillers", "SAW wire + flux, flux-cored, low-hydrogen electrodes, alloy and nickel fillers"],
        ["Codes", "ASME IX / VIII / B31.3, AWS D1.1, API 1104, EN ISO 15614"],
        ["Quality control", "Volumetric NDT (UT/PAUT/RT) required by code, preheat and PWHT records"],
      ],
      insight: "Consumables are qualified into procedures (WPS/PQR) per project, so switching brands means requalification. That creates high switching costs and sticky share once specified.",
    },

    /* =========================== SEGMENTS ========================== */
    {
      id: "seg_auto", layer: "segment", name: "Automotive & EV", tiers: ["tier_light"],
      sum: "Very high automation. Most body joining is resistance spot welding; arc welding concentrates in chassis, exhaust and EV battery structures.",
      intensity: 3, autoLevel: "Very high", growth: "Moderate",
      drivers: "EV platforms, lightweighting (aluminum, AHSS), gigacasting that removes welds, reshoring of battery plants",
      codes: "OEM standards; AWS D8.8 (arc welding of chassis)",
      apps: [
        ["app_chassis", 5, "Largest arc-welding pool: subframes, control arms, axles, seat frames"],
        ["app_battery", 4, "Growth area: aluminum trays and e-motor housings"],
        ["app_biw", 3, "Mostly resistance spot and laser; arc welding is a small share"],
        ["app_exhaust", 3, "Stainless metal-cored and solid wire in robot cells; shrinks with EV mix"],
      ],
      insight: "Gigacasting and adhesives cut weld count per vehicle. Growth is in aluminum battery enclosures and e-drive housings, where pulsed GMAW, laser and friction stir compete.",
    },
    {
      id: "seg_genfab", layer: "segment", name: "General Fabrication & Job Shops", tiers: ["tier_light"],
      sum: "The largest pool of welding machines by unit count: high-mix, low-volume work, bought mostly through distribution.",
      intensity: 4, autoLevel: "Low → Medium (cobots)", growth: "Moderate",
      drivers: "Skilled-welder shortage, reshoring, cobot affordability, quick-turn custom work",
      codes: "AWS D1.1 / D1.3 when structural; often customer drawings only",
      apps: [
        ["app_jobshop", 5, "Brackets, frames, weldments"],
        ["app_enclosure", 3],
        ["app_thinss", 3],
        ["app_alum", 2],
        ["app_mro", 2],
      ],
      insight: "The welder shortage in North America and Europe makes cobots the fastest-growing automation category here. They make automation possible for shops that could never justify a fenced robot cell.",
    },
    {
      id: "seg_hvac", layer: "segment", name: "HVAC, Appliances & Durables", tiers: ["tier_light"],
      sum: "High-volume thin-gauge production. Copper coils are brazed (not arc welded); arc welding covers compressor shells, frames and stainless drums.",
      intensity: 2, autoLevel: "High", growth: "Moderate",
      drivers: "Heat-pump adoption, data-center cooling equipment demand, efficiency regulations",
      codes: "UL / pressure-equipment rules for compressors; OEM specs",
      apps: [
        ["app_hvac", 5],
        ["app_enclosure", 3],
        ["app_thinss", 3],
      ],
    },
    {
      id: "seg_yellow", layer: "segment", name: "Construction, Mining & Ag Equipment", tiers: ["tier_heavy"],
      sum: "Yellow goods: thick high-strength plate welded in robot cells. The biggest robotic arc-welding market outside automotive.",
      intensity: 5, autoLevel: "High", growth: "Moderate (cyclical)",
      drivers: "Infrastructure spending, mining capex, ag cycles, productivity push into robot cells",
      codes: "OEM standards; ISO 5817 quality levels; AWS D14.3 (earthmoving equipment)",
      apps: [
        ["app_boom", 5, "Booms, sticks, buckets: multi-pass thick fillets"],
        ["app_frames", 4],
        ["app_hardface", 2, "Wear protection on buckets and blades"],
      ],
      insight: "Robot cells running metal-cored or high-deposition solid wire in drums. Fatigue-critical welds are moving to PAUT and in-process monitoring.",
    },
    {
      id: "seg_transport", layer: "segment", name: "Rail, Truck, Trailer & Bus", tiers: ["tier_heavy", "tier_light"],
      sum: "Long seams and repeatable frames in steel and aluminum. Rail is certification-driven (EN 15085, AAR).",
      intensity: 4, autoLevel: "Medium", growth: "Moderate",
      drivers: "Freight car cycles, transit investment, aluminum lightweighting, EV buses and trucks",
      codes: "EN 15085 (rail, EU), AAR M-1001 (railcars, NA), AWS D15.1",
      apps: [
        ["app_railcar", 5],
        ["app_frames", 4],
        ["app_alum", 3],
      ],
    },
    {
      id: "seg_ship", layer: "segment", name: "Shipbuilding & Offshore", tiers: ["tier_heavy"],
      sum: "Panel lines, block assembly and all-position erection welding. Rutile flux-cored wire is the workhorse.",
      intensity: 5, autoLevel: "Medium", growth: "Moderate → High",
      drivers: "Naval build-up (e.g. the US submarine industrial base), LNG carriers, offshore wind vessels",
      codes: "Class society rules (ABS, DNV, LR, BV); NAVSEA tech pubs for naval work",
      apps: [
        ["app_panel", 5, "One-sided SAW and gantry fillet welding"],
        ["app_erection", 5, "Out-of-position FCAW with carriages"],
        ["app_offjacket", 3],
        ["app_alum", 2, "Fast ferries, patrol craft"],
        ["app_cryo", 2, "LNG containment systems"],
      ],
      insight: "Asian yards (China, Korea, Japan) dominate tonnage. In North America the naval programs are the growth pocket, with strict NAVSEA qualification and a lot of FCAW and GMAW.",
    },
    {
      id: "seg_pipeline", layer: "segment", name: "Oil & Gas Pipelines", tiers: ["tier_heavy"],
      sum: "Cross-country mainline spreads, yard double-jointing and pipe mills. Productivity is measured in welds per day.",
      intensity: 4, autoLevel: "Medium", growth: "Moderate",
      drivers: "Gas transmission, LNG feed lines, CO2 and hydrogen pipelines, replacement programs",
      codes: "API 1104, CSA Z662, DNV-ST-F101 (offshore), ISO 13847",
      apps: [
        ["app_girth", 5, "Mainline girth welds: stick (stovepipe) or mechanized GMAW"],
        ["app_pipemill", 4, "Longitudinal and spiral SAW seams at the mill"],
        ["app_doublejoint", 3],
        ["app_mro", 1],
      ],
      insight: "Cellulosic stick still dominates small and medium spreads. Large-diameter projects favor mechanized GMAW with automated UT. Pipe mills are a separate, very high-volume SAW wire and flux market.",
    },
    {
      id: "seg_process", layer: "segment", name: "Petrochem, Refining & Chemical", tiers: ["tier_heavy"],
      sum: "Process piping spools, pressure equipment and corrosion-resistant overlays, all under ASME codes and owner specs.",
      intensity: 4, autoLevel: "Medium", growth: "Moderate",
      drivers: "Turnarounds, chemical capacity additions, decarbonization retrofits (blue hydrogen, CCUS)",
      codes: "ASME B31.3, ASME VIII, API 582, API 650",
      apps: [
        ["app_spool", 5],
        ["app_vessel", 4],
        ["app_overlay", 3],
        ["app_tts", 3],
        ["app_mro", 3, "Shutdowns and turnarounds"],
        ["app_tank", 2],
      ],
    },
    {
      id: "seg_power", layer: "segment", name: "Power Generation", tiers: ["tier_heavy"],
      sum: "Boilers, heat-recovery steam generators, nuclear islands and power piping. High-alloy steels (P91/P92) and nickel fillers.",
      intensity: 4, autoLevel: "Medium", growth: "Moderate → High",
      drivers: "Gas turbines and HRSGs to power data centers, nuclear life extension, SMRs, grid build-out",
      codes: "ASME I, III (nuclear), B31.1",
      apps: [
        ["app_boiler", 5],
        ["app_spool", 4],
        ["app_nuclear", 3],
        ["app_tts", 3],
        ["app_overlay", 2],
      ],
      insight: "Data-center power demand is reviving gas-fired and nuclear fabrication. High-alloy and nickel consumables carry premium pricing, and qualified welders are scarce.",
    },
    {
      id: "seg_wind", layer: "segment", name: "Wind Energy", tiers: ["tier_heavy"],
      sum: "Tower and monopile factories are among the largest per-plant consumers of SAW wire and flux.",
      intensity: 5, autoLevel: "High", growth: "High (policy-volatile)",
      drivers: "Offshore wind auctions, larger turbines (thicker, larger-diameter sections), local-content rules",
      codes: "EN 1090, ISO 3834, DNV-ST-0126",
      apps: [
        ["app_windtower", 5],
        ["app_monopile", 4],
      ],
      insight: "Tandem and multi-wire SAW on column and boom with flux recovery. Demand swings with offshore auction cycles and project cancellations.",
    },
    {
      id: "seg_struct", layer: "segment", name: "Structural Steel, Buildings & Bridges", tiers: ["tier_heavy"],
      sum: "Shop fabrication of beams and girders plus field erection. Field work favors self-shielded flux-cored wire.",
      intensity: 4, autoLevel: "Medium (robotic beam lines rising)", growth: "Moderate → High",
      drivers: "Reshored factories, data centers, warehouses, infrastructure funding, seismic codes",
      codes: "AWS D1.1, D1.5 (bridges), D1.8 (seismic), EN 1090",
      apps: [
        ["app_builtup", 5],
        ["app_fieldconn", 4],
        ["app_bridge", 3],
      ],
    },
    {
      id: "seg_dc", layer: "segment", name: "Data Centers & AI Infrastructure", tiers: ["tier_heavy", "tier_light"],
      sum: "Most welding goes into structural steel, large-bore chilled-water piping and off-site prefab (skids, gensets, electrical enclosures). Orbital GTAW is a smaller but fast-growing slice tied to liquid cooling.",
      intensity: 3, autoLevel: "Low → Medium", growth: "Very high",
      drivers: "AI capex, direct-to-chip liquid cooling, modular and prefabricated construction, on-site power generation",
      codes: "AWS D1.1 (structural), ASME B31.9 / B31.3 (piping), NFPA / UL for electrical equipment",
      apps: [
        ["app_chw", 5, "Chilled-water and condenser piping: largest weld-inch pool"],
        ["app_dcstruct", 4, "Building frame, mezzanines, equipment platforms"],
        ["app_skid", 4, "Prefab pump and cooling skids, genset bases, fuel systems"],
        ["app_enclosure", 4, "Switchgear, busway, UPS and e-house enclosures (light fab)"],
        ["app_liquid", 3, "Stainless TCS and CDU loops: orbital GTAW, fastest growth"],
      ],
      insight: "Correction to the starting assumption: orbital TIG is not the main weld volume in a data-center build. It is concentrated in stainless liquid-cooling loops and skid prefab. By weld volume, structural FCAW and SMAW plus large-bore carbon-steel piping (GTAW or SMAW root, FCAW or GMAW fill) lead, and grooved or press-fit mechanical joints compete with welding on smaller pipe. Upstream power (gas turbines, substations, transformers) also pulls through Power Generation.",
    },
    {
      id: "seg_semi", layer: "segment", name: "Semiconductor Fabs & Electronics", tiers: ["tier_light", "tier_heavy"],
      sum: "The heartland of orbital GTAW: thousands of autogenous 316L electropolished tube welds per fab, each logged and checked with coupons.",
      intensity: 3, autoLevel: "High (orbital)", growth: "High",
      drivers: "Fab construction (CHIPS Act in the US, EU Chips Act), tool hook-up waves, specialty gas systems",
      codes: "SEMI F78 / F81, ASME BPE, owner specs",
      apps: [
        ["app_uhp", 5, "Tool hook-up and bulk gas lines"],
        ["app_spool", 3, "Process cooling water, exhaust and chemical piping"],
        ["app_builtup", 2, "Fab building structure"],
      ],
    },
    {
      id: "seg_food", layer: "segment", name: "Food, Beverage, Dairy & Pharma", tiers: ["tier_light"],
      sum: "Hygienic stainless piping and vessels. Crevice-free, smooth welds with low heat tint, verified by borescope.",
      intensity: 3, autoLevel: "Medium", growth: "Moderate (biopharma high)",
      drivers: "Biopharma capacity, GLP-1 drug manufacturing, food plant automation",
      codes: "ASME BPE, 3-A Sanitary Standards",
      apps: [
        ["app_sanitary", 5],
        ["app_thinss", 4],
      ],
    },
    {
      id: "seg_aero", layer: "segment", name: "Aerospace & Defense", tiers: ["tier_light", "tier_heavy"],
      sum: "Precision welding of titanium and nickel superalloys (aero) plus armor and naval steels (defense).",
      intensity: 2, autoLevel: "Medium", growth: "High (defense)",
      drivers: "Defense budgets, munitions and armored vehicle production, engine MRO",
      codes: "AWS D17.1 (aerospace), NAVSEA Tech Pubs 248 / 278, MIL specs",
      apps: [
        ["app_aero", 5],
        ["app_defense", 4],
      ],
    },
    {
      id: "seg_pv", layer: "segment", name: "Pressure Vessels, Boilers & Tanks", tiers: ["tier_heavy"],
      sum: "Classic column-and-boom SAW territory: longitudinal and circumferential seams on rotators, plus cladding and field-erected tanks.",
      intensity: 5, autoLevel: "High", growth: "Moderate",
      drivers: "Refining and chemical capex, LNG, hydrogen storage, water infrastructure",
      codes: "ASME VIII Div 1/2, EN 13445, API 650 / 620",
      apps: [
        ["app_vessel", 5],
        ["app_tank", 4],
        ["app_overlay", 3],
        ["app_tts", 3],
        ["app_cryo", 2],
      ],
    },
    {
      id: "seg_mining", layer: "segment", name: "Mining, Cement & Heavy Maintenance", tiers: ["tier_heavy"],
      sum: "Consumables-led and service-heavy: hardfacing wear parts and keeping plants running.",
      intensity: 3, autoLevel: "Low", growth: "Moderate",
      drivers: "Commodity cycles, critical minerals, uptime economics",
      codes: "Mostly owner specs; AWS D1.1 for structural repairs",
      apps: [
        ["app_hardface", 5],
        ["app_mro", 5],
        ["app_boom", 2],
      ],
      insight: "Hardfacing alloys are sold on wear-life performance, not price per kilo. Strong aftermarket and distribution pull.",
    },
    {
      id: "seg_lng", layer: "segment", name: "LNG, Hydrogen & CCUS", tiers: ["tier_heavy"],
      sum: "Cryogenic and energy-transition equipment: 9% nickel tanks, stainless piping and hydrogen- or CO2-compatible procedures.",
      intensity: 4, autoLevel: "Medium", growth: "High",
      drivers: "LNG export build-out, hydrogen hubs, carbon capture pipelines",
      codes: "API 620 / 625, ASME B31.12 (hydrogen), EN 14620",
      apps: [
        ["app_cryo", 5],
        ["app_spool", 4],
        ["app_vessel", 3],
        ["app_tank", 3],
        ["app_girth", 2, "CO2 and hydrogen pipelines"],
      ],
    },

    /* ========================= APPLICATIONS ======================== */
    {
      id: "app_biw", layer: "app", name: "Body-in-white & closures",
      sum: "Car body structure. Resistance spot welding does most of the joining (thousands of spots per car), with laser and some arc seams.",
      mat: "Coated AHSS/UHSS and aluminum, 0.7–2 mm",
      processes: ["proc_rsw", "proc_laser", "proc_gmaw"],
      automation: ["auto_robot"],
      fillers: ["fil_none", "fil_solid_cs"],
      ndt: ["ndt_ut", "ndt_monitor", "ndt_vt"],
      steps: ["Stamped panels loaded into fixtures", "Robotic spot, laser and MIG stations", "Adaptive weld controllers log every spot", "Sample teardown and ultrasonic spot checks", "Paint shop"],
    },
    {
      id: "app_chassis", layer: "app", name: "Chassis, suspension & seat frames",
      sum: "Subframes, control arms, axles and seat structures welded in high-volume robot cells.",
      mat: "HSLA and AHSS steel, 2–6 mm, often galvanized",
      processes: ["proc_gmaw"],
      automation: ["auto_robot"],
      fillers: ["fil_solid_cs", "fil_mcw"],
      ndt: ["ndt_vt", "ndt_monitor"],
      steps: ["Part load into twin-station fixture", "Robot GMAW (pulsed or short-circuit), touch sensing", "Arc data monitored per weld", "Cut-and-etch macro samples per shift", "Visual check and ship"],
    },
    {
      id: "app_exhaust", layer: "app", name: "Exhaust systems",
      sum: "Thin ferritic stainless tubes, flanges and catalytic converter housings.",
      mat: "409 / 439 ferritic stainless, 1–2 mm",
      processes: ["proc_gmaw"],
      automation: ["auto_robot"],
      fillers: ["fil_mcw", "fil_solid_ss"],
      ndt: ["ndt_leak", "ndt_vt"],
      steps: ["Tube bending and forming", "Robot GMAW with stainless metal-cored wire", "Leak test", "Visual check"],
    },
    {
      id: "app_battery", layer: "app", name: "EV battery trays & e-motor housings",
      sum: "Aluminum extrusion and casting assemblies that must be leak-tight and dimensionally precise.",
      mat: "6xxx aluminum extrusions and castings, 2–5 mm",
      processes: ["proc_gmaw", "proc_fsw", "proc_laser"],
      automation: ["auto_robot", "auto_special"],
      fillers: ["fil_al", "fil_none"],
      ndt: ["ndt_leak", "ndt_rt", "ndt_vt", "ndt_monitor"],
      steps: ["Fixture extrusions", "Pulsed GMAW, FSW or laser joining", "Machining of sealing faces", "Helium or pressure-decay leak test", "CT or X-ray sampling for porosity"],
    },
    {
      id: "app_jobshop", layer: "app", name: "Job-shop brackets, frames & weldments",
      sum: "High-mix, low-volume carbon-steel fabrication. The core of distribution sales and prime cobot territory.",
      mat: "Mild steel, 3–12 mm",
      processes: ["proc_gmaw", "proc_fcawg", "proc_smaw", "proc_gtaw"],
      automation: ["auto_semi", "auto_cobot", "auto_manual"],
      fillers: ["fil_solid_cs", "fil_fcawg", "fil_mcw", "fil_lowh"],
      ndt: ["ndt_vt", "ndt_mt"],
      steps: ["Cut and bend (plasma, laser, saw)", "Tack in fixtures", "Weld semi-auto MIG or on a cobot table", "Grind and visual check", "Paint or powder coat"],
    },
    {
      id: "app_enclosure", layer: "app", name: "Electrical enclosures, switchgear & e-houses",
      sum: "Sheet-metal cabinets, switchgear, busway and UPS housings. Demand is surging with data centers and grid spending.",
      mat: "Mild steel, stainless and aluminum sheet, 1.5–3 mm",
      processes: ["proc_gmaw", "proc_gtaw", "proc_laser"],
      automation: ["auto_semi", "auto_cobot", "auto_robot"],
      fillers: ["fil_solid_cs", "fil_solid_ss", "fil_tig"],
      ndt: ["ndt_vt"],
      steps: ["Laser cut and press-brake", "Tack and stitch weld (MIG short-circuit or pulsed)", "TIG on visible stainless seams", "Grind and finish", "Assemble electrical content"],
    },
    {
      id: "app_thinss", layer: "app", name: "Thin-gauge stainless fabrication",
      sum: "Food equipment, appliance drums, kitchen and process equipment where the weld is visible and must stay clean.",
      mat: "304/316 stainless, 0.8–4 mm",
      processes: ["proc_gtaw", "proc_gmaw", "proc_paw", "proc_laser"],
      automation: ["auto_manual", "auto_cobot", "auto_special"],
      fillers: ["fil_tig", "fil_solid_ss", "fil_none"],
      ndt: ["ndt_vt", "ndt_pt"],
      steps: ["Shear, form, roll", "Manual TIG, cobot TIG or seamer", "Passivate and pickle heat tint", "Visual and dye-penetrant checks"],
    },
    {
      id: "app_hvac", layer: "app", name: "HVAC units, compressors & appliance frames",
      sum: "Compressor shells, unit frames and brackets. Copper coils are brazed, which is outside arc welding.",
      mat: "Carbon steel shells 2–6 mm, galvanized sheet",
      processes: ["proc_gmaw", "proc_saw"],
      automation: ["auto_robot", "auto_special"],
      fillers: ["fil_solid_cs", "fil_saw"],
      ndt: ["ndt_leak", "ndt_vt"],
      steps: ["Deep-draw shell halves", "Circumferential GMAW or SAW on a special machine", "Pressure and leak test", "Final assembly"],
    },
    {
      id: "app_boom", layer: "app", name: "Booms, arms, buckets & heavy frames",
      sum: "Multi-pass fillet and groove welds on thick quenched-and-tempered plate in large robot cells with positioners.",
      mat: "Q&T and HSLA steel, 10–50 mm",
      processes: ["proc_gmaw", "proc_fcawg", "proc_saw"],
      automation: ["auto_robot", "auto_semi", "auto_cab"],
      fillers: ["fil_mcw", "fil_solid_cs", "fil_fcawg", "fil_saw"],
      ndt: ["ndt_vt", "ndt_mt", "ndt_paut", "ndt_monitor"],
      steps: ["Plate cutting and bevelling", "Tack-up in fixtures", "Preheat if thick", "Robot multi-pass welding on two-axis positioner", "MT or PAUT on fatigue-critical welds", "Paint"],
    },
    {
      id: "app_frames", layer: "app", name: "Truck, trailer & equipment frames",
      sum: "Long rails, crossmembers and sub-assemblies. Mix of robots for repeat parts and semi-auto for variants.",
      mat: "HSLA steel, 5–12 mm",
      processes: ["proc_gmaw", "proc_fcawg"],
      automation: ["auto_robot", "auto_semi", "auto_tractor"],
      fillers: ["fil_solid_cs", "fil_mcw", "fil_fcawg"],
      ndt: ["ndt_vt", "ndt_mt"],
      steps: ["Rail forming and punching", "Fixture assembly", "Robot or semi-auto GMAW", "Visual and MT sampling", "E-coat and paint"],
    },
    {
      id: "app_railcar", layer: "app", name: "Railcar bodies & bogies",
      sum: "Center sills, side sills and tank cars in steel; bogie frames with high fatigue demands.",
      mat: "Carbon and HSLA steel 6–25 mm; aluminum for some car bodies",
      processes: ["proc_saw", "proc_gmaw", "proc_fcawg"],
      automation: ["auto_gantry", "auto_robot", "auto_tractor", "auto_semi"],
      fillers: ["fil_saw", "fil_solid_cs", "fil_fcawg", "fil_mcw"],
      ndt: ["ndt_vt", "ndt_mt", "ndt_ut"],
      steps: ["Sill and sheet prep", "Long seams with SAW or tractor FCAW", "Bogie frames in robot cells", "UT and MT on fatigue-critical welds", "Certification records (AAR / EN 15085)"],
    },
    {
      id: "app_alum", layer: "app", name: "Aluminum structures (boats, trailers, railcars)",
      sum: "Welding aluminum extrusions and plate needs push-pull feeding, pulsed MIG and tight cleanliness control.",
      mat: "5xxx / 6xxx aluminum, 3–20 mm",
      processes: ["proc_gmaw", "proc_fsw", "proc_gtaw"],
      automation: ["auto_semi", "auto_robot", "auto_tractor", "auto_special"],
      fillers: ["fil_al", "fil_none", "fil_tig"],
      ndt: ["ndt_vt", "ndt_pt", "ndt_rt"],
      steps: ["Oxide removal and cleaning", "Pulsed MIG (push-pull gun) or FSW of panels", "Distortion control and straightening", "PT or RT per class rules"],
    },
    {
      id: "app_panel", layer: "app", name: "Ship hull panels & blocks (panel line)",
      sum: "Flat plates butt-welded by one-sided SAW, then stiffeners fillet-welded by multi-head gantries.",
      mat: "Shipbuilding steel (AH36 / DH36), 8–30 mm",
      processes: ["proc_saw", "proc_fcawg", "proc_gmaw", "proc_laser"],
      automation: ["auto_gantry", "auto_tractor"],
      fillers: ["fil_saw", "fil_fcawg", "fil_mcw"],
      ndt: ["ndt_vt", "ndt_ut", "ndt_rt"],
      steps: ["Plate joining: one-sided SAW on flux or ceramic backing", "Marking", "Stiffener fillets: gantry with multiple FCAW or GMAW torches", "Block assembly", "Spot UT or RT per class"],
    },
    {
      id: "app_erection", layer: "app", name: "Hull erection & out-of-position seams",
      sum: "Joining blocks in the dock: vertical, overhead and horizontal seams, mostly with rutile flux-cored wire.",
      mat: "Shipbuilding steel, 10–40 mm",
      processes: ["proc_fcawg", "proc_smaw", "proc_esw"],
      automation: ["auto_semi", "auto_tractor", "auto_manual"],
      fillers: ["fil_fcawg", "fil_lowh"],
      ndt: ["ndt_vt", "ndt_ut", "ndt_mt"],
      steps: ["Block fit-up with strongbacks", "Ceramic backing strips", "FCAW with rail carriages (vertical-up) or electrogas", "Back-gouge where needed", "UT on critical seams"],
    },
    {
      id: "app_offjacket", layer: "app", name: "Offshore jackets, nodes & topsides",
      sum: "Thick tubular joints with high toughness and fatigue demands, much of it UT-inspected at 100%.",
      mat: "Offshore steels (S355–S460 ML/QL), 25–100+ mm",
      processes: ["proc_fcawg", "proc_smaw", "proc_saw", "proc_gtaw"],
      automation: ["auto_semi", "auto_manual", "auto_cab", "auto_tractor"],
      fillers: ["fil_fcawg", "fil_lowh", "fil_saw", "fil_tig"],
      ndt: ["ndt_ut", "ndt_paut", "ndt_tofd", "ndt_mt"],
      steps: ["Roll and SAW tubular cans on column and boom", "Node fit-up (complex saddles)", "Preheat and multi-pass FCAW or SMAW", "PWHT on thick nodes", "100% UT or PAUT and MT"],
    },
    {
      id: "app_girth", layer: "app", name: "Pipeline mainline girth welds",
      sum: "Welding pipe joints in the field, either stick welded vertical-down (stovepipe) or with mechanized GMAW spreads.",
      mat: "API 5L X52–X80 line pipe, 6–60 in diameter",
      processes: ["proc_smaw", "proc_gmaw", "proc_fcaws"],
      automation: ["auto_manual", "auto_mechpipe", "auto_semi"],
      fillers: ["fil_cell", "fil_lowh", "fil_solid_cs", "fil_fcaws"],
      ndt: ["ndt_aut", "ndt_rt", "ndt_vt"],
      steps: ["Bevel and line-up (internal clamp)", "Root: cellulosic stick or internal GMAW welder", "Hot pass within minutes", "Fill and cap (stick, FCAW-S or GMAW bugs)", "AUT or RT on 100% of welds", "Coat field joint"],
    },
    {
      id: "app_doublejoint", layer: "app", name: "Pipe double-jointing (yard)",
      sum: "Two pipe lengths welded into one in a yard to halve the number of field welds.",
      mat: "Line pipe, 12–60 in",
      processes: ["proc_saw", "proc_gmaw"],
      automation: ["auto_cab", "auto_special"],
      fillers: ["fil_saw", "fil_solid_cs"],
      ndt: ["ndt_aut", "ndt_rt"],
      steps: ["Line-up on rollers", "GMAW root", "SAW fill and cap while pipe rotates", "AUT or RT", "Transport to right-of-way"],
    },
    {
      id: "app_pipemill", layer: "app", name: "Pipe mill longitudinal & spiral seams",
      sum: "Large-diameter pipe made from plate or coil and welded with multi-wire SAW inside and outside.",
      mat: "API 5L plate or coil, 8–40 mm",
      processes: ["proc_saw", "proc_gmaw"],
      automation: ["auto_special"],
      fillers: ["fil_saw", "fil_solid_cs"],
      ndt: ["ndt_ut", "ndt_rt"],
      steps: ["Plate forming (UOE / JCOE) or spiral forming", "Continuous GMAW tack", "Inside and outside multi-wire SAW (3–5 wires)", "Automated UT and X-ray of seam", "Hydrotest"],
    },
    {
      id: "app_spool", layer: "app", name: "Process piping spools",
      sum: "Prefabricated pipe spools in carbon, stainless and chrome-moly steel: TIG root and faster fill, rolled on positioners in the shop.",
      mat: "CS, SS, Cr-Mo (P11/P22/P91), duplex; 1/2–48 in",
      processes: ["proc_gtaw", "proc_smaw", "proc_fcawg", "proc_gmaw", "proc_saw"],
      automation: ["auto_manual", "auto_semi", "auto_positioner", "auto_orbpipe", "auto_cab"],
      fillers: ["fil_tig", "fil_lowh", "fil_fcawg", "fil_solid_cs", "fil_solid_ss", "fil_saw", "fil_ni"],
      ndt: ["ndt_rt", "ndt_paut", "ndt_vt", "ndt_pt", "ndt_mt"],
      steps: ["Cut, bevel and fit per isometric", "Purge (stainless/alloy) and TIG or advanced-waveform MIG root", "Roll on positioner: FCAW, GMAW or SAW fill and cap", "Preheat and PWHT for Cr-Mo", "RT or PAUT per B31.3 category", "Hydrotest and ship to site"],
    },
    {
      id: "app_vessel", layer: "app", name: "Pressure vessel shells & heads",
      sum: "Longitudinal and circumferential seams with SAW on column and boom and turning rolls, often narrow-gap on thick walls.",
      mat: "SA-516, Cr-Mo (SA-387), stainless; 12–300 mm",
      processes: ["proc_saw", "proc_smaw", "proc_gtaw", "proc_fcawg"],
      automation: ["auto_cab", "auto_positioner", "auto_manual", "auto_semi"],
      fillers: ["fil_saw", "fil_lowh", "fil_tig", "fil_fcawg"],
      ndt: ["ndt_rt", "ndt_paut", "ndt_tofd", "ndt_mt", "ndt_ut"],
      steps: ["Roll plate into shells", "Long seam SAW (inside, back-gouge, outside)", "Circ seams on rotators with column and boom", "Nozzles by SMAW, FCAW or TIG", "PWHT", "RT or UT (PAUT/TOFD) and hydrotest"],
    },
    {
      id: "app_overlay", layer: "app", name: "Corrosion-resistant overlay & cladding",
      sum: "Depositing stainless or nickel alloy onto carbon-steel vessels, valves and pipe to resist corrosion.",
      mat: "CS or low-alloy base; 309L/347/625 overlay 3–10 mm",
      processes: ["proc_esw", "proc_saw", "proc_gtaw", "proc_gmaw"],
      automation: ["auto_special", "auto_cab", "auto_robot"],
      fillers: ["fil_strip", "fil_ni", "fil_solid_ss", "fil_tig"],
      ndt: ["ndt_pt", "ndt_ut", "ndt_et"],
      steps: ["Surface prep", "Strip cladding (ESW or SAW) on large areas", "Hot-wire TIG or CMT-style MIG on bores and valves", "Chemistry and ferrite checks", "PT on surface, UT for bond"],
    },
    {
      id: "app_tts", layer: "app", name: "Tube-to-tubesheet welds (heat exchangers)",
      sum: "Hundreds to thousands of small tube-end welds per exchanger, done with orbital GTAW heads inserted into each tube.",
      mat: "CS, SS, duplex, titanium, nickel alloy tubes",
      processes: ["proc_gtaw"],
      automation: ["auto_orbtube", "auto_manual"],
      fillers: ["fil_tig", "fil_none"],
      ndt: ["ndt_pt", "ndt_leak", "ndt_vt", "ndt_ettube"],
      steps: ["Tube expansion", "Orbital TTS head (autogenous or with wire)", "PT and leak test (helium or air)", "In service: eddy-current tube inspection during outages"],
    },
    {
      id: "app_boiler", layer: "app", name: "Boiler waterwalls & tube panels",
      sum: "Membrane panels (tube plus fin bar) welded on multi-torch machines, then tube butt welds in shop and field.",
      mat: "Carbon and Cr-Mo tubes (T11–T92), 38–76 mm OD",
      processes: ["proc_gmaw", "proc_saw", "proc_gtaw", "proc_smaw"],
      automation: ["auto_special", "auto_orbpipe", "auto_manual"],
      fillers: ["fil_solid_cs", "fil_saw", "fil_tig", "fil_lowh"],
      ndt: ["ndt_rt", "ndt_ut", "ndt_paut", "ndt_ettube"],
      steps: ["Multi-torch panel welding (GMAW or SAW)", "Orbital or manual TIG tube butt welds", "RT or PAUT of tube butts", "Field erection welds", "In service: tube ET or UT thickness surveys"],
    },
    {
      id: "app_nuclear", layer: "app", name: "Nuclear primary & safety-class piping",
      sum: "Narrow-gap mechanized TIG on heavy-wall stainless and dissimilar-metal welds with full traceability.",
      mat: "Austenitic stainless, low-alloy, nickel-alloy DMWs; 25–100 mm wall",
      processes: ["proc_gtaw", "proc_smaw"],
      automation: ["auto_orbpipe", "auto_manual"],
      fillers: ["fil_tig", "fil_ni", "fil_lowh"],
      ndt: ["ndt_rt", "ndt_paut", "ndt_ut", "ndt_pt", "ndt_vt"],
      steps: ["Narrow-gap bevel", "Orbital hot-wire TIG with camera monitoring", "In-process records to ASME III / NQA-1", "RT plus PAUT, PT", "Pre-service inspection baseline"],
    },
    {
      id: "app_windtower", layer: "app", name: "Wind tower sections (cans & flanges)",
      sum: "Rolled cans welded with tandem or twin SAW on long and circumferential seams, then flanges.",
      mat: "S355 steel, 20–80 mm; 4–8 m diameter",
      processes: ["proc_saw", "proc_gmaw", "proc_fcawg"],
      automation: ["auto_cab", "auto_positioner", "auto_semi"],
      fillers: ["fil_saw", "fil_solid_cs", "fil_fcawg"],
      ndt: ["ndt_paut", "ndt_ut", "ndt_tofd", "ndt_mt"],
      steps: ["Cut and bevel plate", "Roll into can; tack long seam", "Long seam SAW inside and outside", "Circ seams joining cans on rotators (column and boom)", "Flange welds", "100% UT or PAUT and MT"],
    },
    {
      id: "app_monopile", layer: "app", name: "Monopiles & transition pieces (offshore)",
      sum: "Extra-thick, extra-large sections with multi-wire SAW. Among the most deposition-heavy welding anywhere.",
      mat: "S355 ML/NL, 60–150 mm; up to 10+ m diameter",
      processes: ["proc_saw"],
      automation: ["auto_cab", "auto_special", "auto_positioner"],
      fillers: ["fil_saw"],
      ndt: ["ndt_paut", "ndt_tofd", "ndt_ut", "ndt_mt"],
      steps: ["Narrow-gap or double-V bevels", "Multi-wire SAW (tandem, 3–4 wires) with flux recovery", "Heat input and interpass control", "PAUT plus TOFD at 100%", "Coating"],
    },
    {
      id: "app_builtup", layer: "app", name: "Shop fabrication: beams, columns & plate girders",
      sum: "Web-to-flange SAW on beam lines plus fittings (plates, stiffeners), increasingly with robotic beam assembly.",
      mat: "A992 / A572 / S355, 10–50 mm",
      processes: ["proc_saw", "proc_fcawg", "proc_gmaw"],
      automation: ["auto_gantry", "auto_robot", "auto_semi"],
      fillers: ["fil_saw", "fil_fcawg", "fil_solid_cs", "fil_mcw"],
      ndt: ["ndt_ut", "ndt_mt", "ndt_vt"],
      steps: ["CNC cut, drill, cope", "H-beam line SAW (web to flange)", "Robotic or semi-auto fitting welds", "UT on CJP groove welds, MT on fillets", "Paint and ship"],
    },
    {
      id: "app_fieldconn", layer: "app", name: "Field erection: column splices & moment connections",
      sum: "Outdoor welding at height, where wind blows away shielding gas, so self-shielded flux-cored wire dominates.",
      mat: "Structural steel, 12–75 mm",
      processes: ["proc_fcaws", "proc_smaw", "proc_fcawg"],
      automation: ["auto_semi", "auto_manual", "auto_tractor"],
      fillers: ["fil_fcaws", "fil_lowh", "fil_fcawg"],
      ndt: ["ndt_ut", "ndt_mt", "ndt_vt"],
      steps: ["Erect and bolt up", "Preheat", "FCAW-S demand-critical welds (seismic)", "Back-gouge or backing removal", "UT on CJP welds by third party"],
    },
    {
      id: "app_bridge", layer: "app", name: "Bridge girders & decks",
      sum: "Fracture-critical members under AWS D1.5. Heavy SAW in the shop, with tractors and FCAW for stiffeners.",
      mat: "A709 / weathering steels, 12–100 mm",
      processes: ["proc_saw", "proc_fcawg", "proc_smaw"],
      automation: ["auto_cab", "auto_gantry", "auto_tractor", "auto_semi"],
      fillers: ["fil_saw", "fil_fcawg", "fil_lowh"],
      ndt: ["ndt_ut", "ndt_rt", "ndt_mt", "ndt_paut"],
      steps: ["Flange and web splices (SAW)", "Web-to-flange SAW", "Stiffeners (FCAW, tractor)", "RT or UT of tension splices", "MT on fillets; field splices bolted or welded"],
    },
    {
      id: "app_dcstruct", layer: "app", name: "Data center structural steel & mezzanines",
      sum: "The building frame, equipment platforms, pipe racks and cable-tray supports: classic shop-plus-field structural welding.",
      mat: "A992 / A36 structural steel, 6–40 mm",
      processes: ["proc_fcaws", "proc_fcawg", "proc_smaw", "proc_gmaw"],
      automation: ["auto_semi", "auto_manual", "auto_robot"],
      fillers: ["fil_fcaws", "fil_fcawg", "fil_lowh", "fil_solid_cs"],
      ndt: ["ndt_ut", "ndt_mt", "ndt_vt"],
      steps: ["Shop: beam lines and robot fitting", "Field: erection and FCAW-S or SMAW connections", "Pipe racks and supports", "UT and MT by special inspector"],
    },
    {
      id: "app_chw", layer: "app", name: "Chilled-water & condenser piping (large bore)",
      sum: "Miles of 6–48 in carbon-steel piping feeding chillers, cooling towers and air handlers. The biggest weld-inch pool in a data center.",
      mat: "A53 / A106 carbon steel, Std/XS wall, 6–48 in",
      processes: ["proc_smaw", "proc_gtaw", "proc_fcawg", "proc_gmaw"],
      automation: ["auto_manual", "auto_semi", "auto_positioner", "auto_orbpipe"],
      fillers: ["fil_cell", "fil_lowh", "fil_tig", "fil_fcawg", "fil_solid_cs"],
      ndt: ["ndt_vt", "ndt_rt", "ndt_paut"],
      steps: ["Off-site prefab: spools rolled on positioners", "Root: TIG, stick, or advanced-waveform MIG", "Fill and cap: FCAW-G or GMAW", "Field tie-ins: stick", "Sample RT or PAUT per spec; hydrotest", "Mechanical grooved couplings compete on smaller sizes"],
    },
    {
      id: "app_liquid", layer: "app", name: "Liquid-cooling loops (stainless TCS / CDU)",
      sum: "Direct-to-chip cooling: stainless technology cooling system (TCS) piping, manifolds and CDU skids that must be clean and leak-free. This is where orbital TIG fits.",
      mat: "304L / 316L stainless tube and pipe, 1/2–12 in",
      processes: ["proc_gtaw"],
      automation: ["auto_orbtube", "auto_orbpipe", "auto_manual"],
      fillers: ["fil_none", "fil_tig", "fil_solid_ss"],
      ndt: ["ndt_vt", "ndt_leak", "ndt_rt"],
      steps: ["Cut and face tube squarely", "Purge with argon", "Orbital GTAW (enclosed head for tube, open head with wire for pipe)", "Weld log and coupon per shift", "Borescope ID bead and heat tint", "Pressure and leak test; flush"],
    },
    {
      id: "app_skid", layer: "app", name: "Modular skids, gensets & fuel systems",
      sum: "Off-site built pump and cooling skids, generator bases, fuel tanks and piping. Prefab shops increasingly add cobots.",
      mat: "Carbon-steel structural bases and piping; stainless for cooling",
      processes: ["proc_gmaw", "proc_fcawg", "proc_gtaw", "proc_smaw"],
      automation: ["auto_semi", "auto_cobot", "auto_robot", "auto_positioner"],
      fillers: ["fil_solid_cs", "fil_fcawg", "fil_tig", "fil_solid_ss", "fil_lowh"],
      ndt: ["ndt_vt", "ndt_mt", "ndt_rt", "ndt_leak"],
      steps: ["Base frame fabrication (MIG or FCAW, cobots on repeat bases)", "Piping spools on positioners", "Stainless cooling piping with TIG", "Pressure and leak test", "Factory acceptance test and ship"],
    },
    {
      id: "app_uhp", layer: "app", name: "UHP gas & chemical distribution tubing",
      sum: "Autogenous orbital welding of electropolished 316L tube. Every weld is logged, and coupons are cut and inspected.",
      mat: "316L VAR/EP tube, 1/4–2 in",
      processes: ["proc_gtaw"],
      automation: ["auto_orbtube"],
      fillers: ["fil_none"],
      ndt: ["ndt_vt", "ndt_leak", "ndt_monitor"],
      steps: ["Cleanroom cut and face", "Ultra-high-purity argon purge (ppm O2 monitored)", "Enclosed-head orbital GTAW, autogenous", "Coupon weld at start of shift; borescope", "Helium leak test", "Weld log hand-over to owner"],
    },
    {
      id: "app_sanitary", layer: "app", name: "Sanitary process piping & vessels",
      sum: "Hygienic stainless systems for dairy, beverage and biopharma: smooth, crevice-free welds with verified ID condition.",
      mat: "316L tube, 1/2–6 in; vessels 2–6 mm",
      processes: ["proc_gtaw", "proc_paw"],
      automation: ["auto_orbtube", "auto_manual", "auto_special"],
      fillers: ["fil_none", "fil_tig"],
      ndt: ["ndt_vt", "ndt_leak"],
      steps: ["Cut and face", "Purge", "Orbital GTAW autogenous", "Borescope 100% or sample per ASME BPE", "Passivation and pressure test"],
    },
    {
      id: "app_aero", layer: "app", name: "Aerospace engine & airframe components",
      sum: "Precision welding of titanium and nickel superalloys where defects are measured in fractions of a millimetre.",
      mat: "Ti-6Al-4V, Inconel 718/625, thin wall",
      processes: ["proc_gtaw", "proc_paw", "proc_laser"],
      automation: ["auto_manual", "auto_robot", "auto_special"],
      fillers: ["fil_tig", "fil_ni", "fil_none"],
      ndt: ["ndt_pt", "ndt_rt", "ndt_et", "ndt_ut"],
      steps: ["Chemical clean", "Inert chamber or trailing shield", "Manual or automated TIG, plasma, laser or electron beam", "Fluorescent PT, X-ray, eddy current", "Heat treat and records to AWS D17.1"],
    },
    {
      id: "app_defense", layer: "app", name: "Armored vehicles & naval combatants",
      sum: "High-hardness armor and HY-80/HY-100 hull steels with strict hydrogen and heat-input control.",
      mat: "Armor steel, HY-80/100, 10–75 mm",
      processes: ["proc_gmaw", "proc_fcawg", "proc_smaw"],
      automation: ["auto_robot", "auto_semi", "auto_tractor", "auto_manual"],
      fillers: ["fil_solid_cs", "fil_fcawg", "fil_lowh", "fil_mcw"],
      ndt: ["ndt_ut", "ndt_mt", "ndt_rt"],
      steps: ["Preheat and cleanliness control", "Robot or semi-auto GMAW or FCAW", "Heat-input logging", "UT, MT and RT per NAVSEA or army specs"],
    },
    {
      id: "app_tank", layer: "app", name: "Field-erected storage tanks",
      sum: "API 650/620 tanks: vertical seams by electrogas, horizontal girth seams by automatic SAW girth welders.",
      mat: "A36 / A516 / A537, 6–40 mm shell",
      processes: ["proc_saw", "proc_esw", "proc_fcawg", "proc_smaw"],
      automation: ["auto_tank", "auto_semi", "auto_manual"],
      fillers: ["fil_saw", "fil_fcawg", "fil_lowh", "fil_solid_cs"],
      ndt: ["ndt_rt", "ndt_vt", "ndt_leak", "ndt_ut"],
      steps: ["Floor plates: FCAW or SMAW lap welds", "Vertical shell seams: electrogas machine", "Horizontal girth seams: SAW girth welder (inside and outside)", "Spot RT per API 650", "Vacuum-box floor test; hydrotest"],
    },
    {
      id: "app_hardface", layer: "app", name: "Hardfacing & wear-part rebuild",
      sum: "Depositing wear-resistant alloys on buckets, crusher rolls, mill tables and dredge parts.",
      mat: "Carbon or Mn steel base; chromium- or complex-carbide overlays",
      processes: ["proc_fcaws", "proc_saw", "proc_smaw", "proc_gmaw"],
      automation: ["auto_semi", "auto_special", "auto_manual", "auto_tractor"],
      fillers: ["fil_hard"],
      ndt: ["ndt_vt", "ndt_pt"],
      steps: ["Remove worn material and buffer layer", "Open-arc FCAW or SAW hardfacing (rolls on turning lathes)", "Check-cracking is expected with carbides", "Visual and hardness check"],
    },
    {
      id: "app_mro", layer: "app", name: "Maintenance & repair (plant MRO)",
      sum: "Unplanned and turnaround repairs: portable machines, stick and self-shielded wire, plus in-service inspection.",
      mat: "Everything: carbon, stainless, cast iron, alloys",
      processes: ["proc_smaw", "proc_fcaws", "proc_gtaw", "proc_gmaw"],
      automation: ["auto_manual", "auto_semi"],
      fillers: ["fil_lowh", "fil_rutile", "fil_fcaws", "fil_tig", "fil_ni"],
      ndt: ["ndt_ut", "ndt_mt", "ndt_pt", "ndt_et"],
      steps: ["Inspect and find defect (ET, UT thickness)", "Excavate and repair procedure", "Weld with portable inverter or engine drive", "PT or MT and return to service"],
    },
    {
      id: "app_cryo", layer: "app", name: "Cryogenic & hydrogen service (LNG, 9% Ni, H2)",
      sum: "LNG tank inner shells in 9% nickel steel welded with nickel-base consumables; stainless and H2-compatible piping.",
      mat: "9% Ni steel, 304L/316L, aluminum (Moss-type)",
      processes: ["proc_smaw", "proc_saw", "proc_gtaw", "proc_fcawg"],
      automation: ["auto_manual", "auto_tank", "auto_cab", "auto_semi"],
      fillers: ["fil_ni", "fil_tig", "fil_solid_ss", "fil_saw"],
      ndt: ["ndt_rt", "ndt_paut", "ndt_pt", "ndt_vt"],
      steps: ["Magnetism control on 9% Ni (arc blow)", "Nickel-base SMAW or SAW on shells", "Stainless piping with TIG root", "RT or PAUT, PT", "Cryogenic toughness testing in procedure qualification"],
    },

    /* ========================== PROCESSES ========================== */
    {
      id: "proc_smaw", layer: "process", name: "SMAW (Stick)", alias: "Shielded Metal Arc Welding / MMA",
      sum: "A flux-coated electrode melts to form the weld. The coating makes the shielding gas and slag. Portable, rugged and skill-intensive.",
      how: "A constant-current power source (AC or DC) strikes an arc between the electrode and the work. The core wire melts into the joint while the coating decomposes into gas and slag that protect the weld pool. The welder feeds the rod by hand and replaces it every 30–90 seconds.",
      facts: [
        ["Deposition", "~1–3 kg/h"],
        ["Positions", "All"],
        ["Arc-on time", "10–30% (rod changes, slag removal)"],
        ["Share of filler tonnage", "~15–25% globally (higher in India, SE Asia, Africa; falling in NA/EU)"],
        ["Power source", "CC transformer or inverter; engine drives in the field"],
        ["Skill", "High"],
      ],
      pros: "No gas bottle, wind tolerant, cheap equipment, works on dirty or rusty steel, all positions",
      cons: "Slow, slag removal, hydrogen control needs rod ovens, relies on scarce skilled welders",
      automation: ["auto_manual"],
      fillers: ["fil_cell", "fil_lowh", "fil_rutile", "fil_hard"],
      ndt: ["ndt_vt", "ndt_mt", "ndt_rt", "ndt_ut"],
      ex: "ESAB: OK and Atom Arc electrodes, Renegade stick inverters",
    },
    {
      id: "proc_gmaw", layer: "process", name: "GMAW (MIG/MAG)", alias: "Gas Metal Arc Welding",
      sum: "A continuously fed wire and external shielding gas. The most widely used process and the most automation-friendly.",
      how: "A constant-voltage power source melts a solid or metal-cored wire fed through a gun. Shielding gas protects the pool (Ar/CO2 for steel, Ar or Ar/He for aluminum, Ar with 2% CO2 or O2 for stainless). Transfer modes: short-circuit (thin, out-of-position), spray (thick, flat), pulsed (low spatter, aluminum and stainless, all positions) and controlled short-circuit waveforms for open roots.",
      facts: [
        ["Deposition", "~1–8 kg/h (tandem up to ~15)"],
        ["Positions", "All (mode-dependent)"],
        ["Arc-on time", "Semi-auto 20–40%; robot 60–85%"],
        ["Share of filler tonnage", "~40–50% (solid wire) plus metal-cored"],
        ["Shielding", "Ar/CO2 mixes, Ar, Ar/He"],
        ["Skill", "Low to medium"],
      ],
      pros: "Fast, easy to learn, clean, the natural process for robots and cobots",
      cons: "Wind blows away gas, lack-of-fusion risk in short-circuit on thick plate, needs a gas supply",
      automation: ["auto_semi", "auto_robot", "auto_cobot", "auto_tractor", "auto_mechpipe", "auto_orbpipe", "auto_gantry", "auto_positioner"],
      fillers: ["fil_solid_cs", "fil_solid_ss", "fil_al", "fil_mcw", "fil_ni"],
      ndt: ["ndt_vt", "ndt_ut", "ndt_paut", "ndt_mt", "ndt_monitor"],
      ex: "ESAB: Aristo, Warrior, Rebel; OK Autrod (solid), Coreweld (metal-cored)",
    },
    {
      id: "proc_fcawg", layer: "process", name: "FCAW-G (Gas-shielded flux core)", alias: "Flux-Cored Arc Welding, gas-shielded",
      sum: "A tubular wire filled with flux plus external gas. High deposition in all positions, the shipyard and heavy-fab workhorse.",
      how: "The same equipment as MIG, but the wire is a tube filled with flux and alloy powders. Rutile types form a fast-freezing slag that holds the pool in vertical and overhead positions at high current. Basic types give low hydrogen and high toughness. Shielding is usually 100% CO2 or 75/25 Ar/CO2.",
      facts: [
        ["Deposition", "~2–10 kg/h; far higher than solid wire out of position"],
        ["Positions", "All (rutile types)"],
        ["Share of filler tonnage", "Cored wires ~20–25% combined; highest in Asian shipbuilding"],
        ["Shielding", "CO2 or Ar/CO2"],
        ["Skill", "Medium"],
      ],
      pros: "All-position productivity, tolerant of mill scale and fit-up, good for thick plate",
      cons: "Slag removal, more fume than solid wire, higher cost per kg than solid wire",
      automation: ["auto_semi", "auto_tractor", "auto_robot", "auto_gantry", "auto_positioner"],
      fillers: ["fil_fcawg"],
      ndt: ["ndt_vt", "ndt_ut", "ndt_mt"],
      ex: "ESAB: Dual Shield, OK Tubrod",
    },
    {
      id: "proc_fcaws", layer: "process", name: "FCAW-S (Self-shielded flux core)", alias: "Innershield-type / self-shielded",
      sum: "The flux core makes its own shielding, so no gas bottle is needed. Wind-tolerant choice for field erection, pipelines and hardfacing.",
      how: "The core contains gas formers and deoxidizers (aluminum, magnesium) that shield the arc without external gas. Welders use it with portable wire feeders on engine drives. Classifications like E71T-8 meet seismic demand-critical toughness requirements.",
      facts: [
        ["Deposition", "~2–7 kg/h"],
        ["Positions", "All (type-dependent)"],
        ["Shielding", "None external"],
        ["Where it wins", "Outdoors, at height, no gas logistics"],
      ],
      pros: "No gas, wind tolerant, portable, high deposition in the field",
      cons: "Higher fume, careful procedure for toughness, slag",
      automation: ["auto_semi", "auto_tractor"],
      fillers: ["fil_fcaws", "fil_hard"],
      ndt: ["ndt_vt", "ndt_ut", "ndt_mt"],
      ex: "ESAB: Coreshield",
    },
    {
      id: "proc_gtaw", layer: "process", name: "GTAW (TIG)", alias: "Gas Tungsten Arc Welding",
      sum: "A non-consumable tungsten electrode with inert gas. The highest quality and control, but slow. Used for pipe roots, thin stainless and exotic alloys, and orbital welding.",
      how: "A constant-current source (DC for steels, AC for aluminum) holds an arc from a tungsten electrode under argon. Filler rod is added by hand or by a cold or hot wire feeder, or no filler is used (autogenous). Orbital systems rotate the tungsten around a fixed tube or pipe under program control and log every weld.",
      facts: [
        ["Deposition", "~0.5–1.5 kg/h (hot-wire 2–5)"],
        ["Positions", "All"],
        ["Share of filler tonnage", "~3–5% by weight but high value (stainless, nickel)"],
        ["Shielding", "Argon, Ar/He; backing purge for stainless"],
        ["Skill", "High (manual); low with orbital"],
      ],
      pros: "Cleanest, most controllable welds on any metal; ideal for roots and thin walls",
      cons: "Slow, skill-intensive by hand, sensitive to drafts and contamination",
      automation: ["auto_manual", "auto_orbtube", "auto_orbpipe", "auto_cobot", "auto_robot", "auto_special"],
      fillers: ["fil_tig", "fil_ni", "fil_none"],
      ndt: ["ndt_vt", "ndt_pt", "ndt_rt", "ndt_leak"],
      ex: "ESAB: Rebel EMP, Renegade ET; OK Tigrod",
    },
    {
      id: "proc_saw", layer: "process", name: "SAW (Submerged arc)", alias: "Submerged Arc Welding",
      sum: "The arc burns under a blanket of granular flux. The highest deposition rates and deep penetration, always mechanized.",
      how: "Wire is fed continuously into the joint beneath a layer of flux that melts into protective slag. There is no visible arc and little fume. Configurations: single wire, twin (two wires, one contact tip), tandem (DC lead and AC trail), multi-wire (3–6 wires), narrow-gap, strip cladding and cold-wire additions such as ESAB ICE. Heads ride on column and boom, tractors, gantries or special machines.",
      facts: [
        ["Deposition", "~5–15 kg/h single wire; 25–40+ multi-wire"],
        ["Positions", "Flat and horizontal only (1G/2G, 1F/2F)"],
        ["Thickness", "6–300 mm"],
        ["Share of filler tonnage", "~8–12% (wire), with a similar weight of flux"],
        ["Skill", "Operator, not welder; setup knowledge"],
      ],
      pros: "Highest productivity, excellent mechanical properties, low fume and arc glare",
      cons: "Flat and horizontal only, needs mechanization, flux handling and drying",
      automation: ["auto_cab", "auto_gantry", "auto_tractor", "auto_tank", "auto_special", "auto_positioner"],
      fillers: ["fil_saw", "fil_strip", "fil_hard", "fil_ni"],
      ndt: ["ndt_ut", "ndt_paut", "ndt_tofd", "ndt_rt"],
      ex: "ESAB: A2 / A6 heads, CaB column and boom, ICE; OK Flux, OK Autrod",
    },
    {
      id: "proc_paw", layer: "process", name: "PAW (Plasma arc)", alias: "Plasma Arc Welding",
      sum: "A TIG-like arc squeezed through a nozzle. Keyhole welding of stainless up to ~8 mm in one pass; micro-plasma for foils.",
      how: "A pilot arc and a constricting copper nozzle create a narrow, stiff plasma jet. In keyhole mode it pierces the joint and the pool flows in behind it. Used on tube mills, cryogenic vessels, aerospace and precision parts.",
      facts: [
        ["Deposition", "Low (often autogenous)"],
        ["Thickness", "0.1–8 mm single pass"],
        ["Niche", "Tube mills, thin precision, keyhole stainless"],
      ],
      pros: "Deep single-pass penetration, stable at low current",
      cons: "Complex torch, narrow operating window, mainly mechanized",
      automation: ["auto_special", "auto_robot", "auto_manual"],
      fillers: ["fil_none", "fil_tig"],
      ndt: ["ndt_vt", "ndt_rt", "ndt_pt"],
    },
    {
      id: "proc_esw", layer: "process", name: "ESW / EGW (Electroslag & Electrogas)", alias: "Electroslag, electroslag strip cladding, electrogas",
      sum: "Resistance heating of molten slag (ESW) or a gas-shielded vertical arc (EGW). Single-pass vertical seams on thick plate and high-speed strip cladding.",
      how: "In ESW, current flows through a molten slag bath that melts wire or strip. Copper shoes contain the pool as the machine climbs. Electroslag strip cladding lays wide stainless or nickel strips onto vessel walls quickly with low dilution. Electrogas uses flux-cored or solid wire with gas and climbing shoes for tank and ship side seams.",
      facts: [
        ["Deposition", "~15–35+ kg/h (strip cladding)"],
        ["Positions", "Vertical-up (ESW/EGW); flat (strip)"],
        ["Where", "Tank verticals, ship side shells, vessel cladding"],
      ],
      pros: "Very high productivity for single-pass verticals and cladding",
      cons: "Very high heat input (toughness), special equipment",
      automation: ["auto_special", "auto_tank", "auto_cab"],
      fillers: ["fil_strip", "fil_fcawg", "fil_solid_cs"],
      ndt: ["ndt_ut", "ndt_pt", "ndt_rt"],
    },
    {
      id: "proc_laser", layer: "process", name: "Laser & laser-hybrid", alias: "LBW / Laser-MIG hybrid / handheld laser",
      sum: "A focused beam gives narrow, fast, low-distortion welds. Robotic in automotive, hybrid in shipyards, and handheld lasers are disrupting thin-gauge job shops.",
      how: "Fiber or disk lasers deliver kW-level beams through optics. Remote laser welding scans the beam over car-body flanges. Laser-hybrid combines a laser keyhole with a trailing MIG arc for gap tolerance on thick panels. Handheld fiber-laser welders (mostly from China) are spreading fast in sheet-metal shops.",
      facts: [
        ["Speed", "Several m/min on thin sheet"],
        ["Distortion", "Very low"],
        ["Threat / opportunity", "Handheld lasers substitute for MIG and TIG on thin sheet"],
      ],
      pros: "Speed, low distortion, cosmetic welds",
      cons: "Tight fit-up, laser safety enclosures, high capex (falling fast)",
      automation: ["auto_robot", "auto_special", "auto_manual"],
      fillers: ["fil_none", "fil_solid_cs"],
      ndt: ["ndt_monitor", "ndt_vt", "ndt_rt"],
    },
    {
      id: "proc_fsw", layer: "process", name: "FSW (Friction stir)", alias: "Friction Stir Welding",
      sum: "A solid-state process: a rotating tool stirs aluminum without melting it. Used for battery trays, rail extrusions and ship panels.",
      how: "A shouldered, pinned tool plunges and traverses along the joint, softening and mixing material below its melting point. No filler, gas or fume, and excellent strength in aluminum. Needs rigid machines or heavy-payload robots.",
      facts: [["Filler", "None"], ["Materials", "Aluminum mainly; also copper, some steel"], ["Where", "EV trays, rail cars, ship decks"]],
      pros: "No porosity, excellent aluminum properties, repeatable",
      cons: "High forces, rigid fixtures, exit hole",
      automation: ["auto_special", "auto_robot"],
      fillers: ["fil_none"],
      ndt: ["ndt_paut", "ndt_vt"],
    },
    {
      id: "proc_rsw", layer: "process", name: "RSW (Resistance spot)", alias: "Resistance Spot Welding",
      sum: "Current through clamped sheets makes a nugget. Thousands of spots per car body; no filler.",
      how: "Copper electrodes squeeze the sheets while a short high-current pulse melts a nugget at the interface. Robotic weld guns with adaptive controllers dominate automotive body shops.",
      facts: [["Spots per car", "~3,000–5,000"], ["Filler", "None"], ["Where", "Automotive BIW, appliances"]],
      pros: "Very fast, no consumables other than electrode caps",
      cons: "Lap joints only, access for both sides",
      automation: ["auto_robot", "auto_special"],
      fillers: ["fil_none"],
      ndt: ["ndt_ut", "ndt_monitor"],
    },

    /* ========================== AUTOMATION ========================= */
    {
      id: "auto_manual", layer: "automation", name: "Manual (handheld)", mode: "manual",
      sum: "The welder controls everything: the torch or electrode, travel speed and filler. Stick and manual TIG.",
      how: "The baseline for field, repair and pipe roots. Productivity depends on welder skill and arc-on time.",
      facts: [["Arc-on time", "10–30%"], ["Capex", "Lowest"], ["Constraint", "Skilled-welder shortage"]],
    },
    {
      id: "auto_semi", layer: "automation", name: "Semi-automatic (wire-fed gun)", mode: "manual",
      sum: "The machine feeds the wire; the welder guides the gun. The default in most fabrication shops.",
      how: "MIG and flux-cored welding with a handheld gun and a wire feeder. The biggest installed base of welding equipment. Pairs with positioners for higher arc-on time.",
      facts: [["Arc-on time", "20–40%"], ["Capex", "Low"], ["Channel", "Mostly distribution"]],
      ex: "ESAB: Warrior, Aristo, Rebel",
    },
    {
      id: "auto_tractor", layer: "automation", name: "Tractors & carriages", mode: "mech",
      sum: "A portable carriage carries the gun or SAW head along the seam on a rail, magnets or wheels, with optional weave.",
      how: "The operator sets speed, weave and angle; the carriage keeps them constant. Quick payback on long straight or gently curved seams. Used in shipyards, tanks, structural and bridges.",
      facts: [["Arc-on time", "40–60%"], ["Capex", "Low–medium"], ["Setup", "Minutes"]],
      ex: "ESAB: Railtrac, Miggytrac, A2 Multitrac / A6 Mastertrac (SAW)",
    },
    {
      id: "auto_cab", layer: "automation", name: "Column & boom + rotators", mode: "mech",
      sum: "A SAW head on a boom that moves in and out and up and down on a column, with the part turning on rotators (circ seams) or the boom travelling (long seams).",
      how: "The standard heavy-fabrication cell for vessels, wind towers, pipe and tanks. Adds flux recovery, seam tracking, cameras and tandem or twin heads. Often built as a complete system with turning rolls and positioners.",
      facts: [["Arc-on time", "50–70%"], ["Capex", "High"], ["Segments", "Pressure vessels, wind, pipe, offshore"]],
      ex: "ESAB: CaB column and boom with A6 heads",
    },
    {
      id: "auto_gantry", layer: "automation", name: "Gantry & panel lines", mode: "mech",
      sum: "A bridge over the work carrying multiple torches: stiffener fillet welding, one-sided SAW panel lines and H-beam lines.",
      how: "Welds several long seams at once on large flat assemblies. The core of shipyard panel shops, bridge girders and beam fabrication.",
      facts: [["Torches", "2–8+"], ["Capex", "High"]],
    },
    {
      id: "auto_positioner", layer: "automation", name: "Pipe positioners & turning rolls", mode: "mech",
      sum: "Rotate the work under a fixed torch so the weld is always flat (1G). The simplest productivity jump in spool shops.",
      how: "Headstock positioners or roller beds turn pipe or vessels at a controlled speed. The welder or a mounted torch stays still. Often packaged with semi-auto GMAW or FCAW, or with SAW.",
      facts: [["Gain", "Large vs fixed-position welding"], ["Capex", "Low–medium"]],
    },
    {
      id: "auto_orbtube", layer: "automation", name: "Orbital GTAW: enclosed head (tube)", mode: "mech",
      sum: "A closed head clamps around the tube and the tungsten rotates 360° in an argon-filled chamber. Autogenous and fully programmed.",
      how: "The power supply runs a stored schedule (pulsed current by sector) and prints or uploads a weld log. The welder becomes an operator. Tube 1/8–6 in. Used in semiconductor UHP, pharma, aerospace hydraulics and liquid-cooling tube.",
      facts: [["Repeatability", "Very high"], ["Output", "Weld log per weld"], ["Capex", "Medium"]],
      ex: "Market examples: Swagelok, Arc Machines, Polysoude, Axxair",
    },
    {
      id: "auto_orbpipe", layer: "automation", name: "Orbital open-head (pipe, with wire)", mode: "mech",
      sum: "A bug on a track clamped around the pipe, with wire feed, arc voltage control and oscillation. TIG (often hot-wire), MIG or FCAW.",
      how: "For larger and thicker pipe in power, process, nuclear and prefab spool shops. Remote cameras let one operator run more than one head. Narrow-gap bevels cut weld volume.",
      facts: [["Pipe size", "~2 in and up"], ["Process", "GTAW (hot/cold wire), GMAW, FCAW"]],
    },
    {
      id: "auto_mechpipe", layer: "automation", name: "Mechanized pipeline systems", mode: "mech",
      sum: "Internal line-up clamps with root welding heads, plus external dual-torch GMAW bugs running on bands around the pipe.",
      how: "A spread runs as a production line: root station, hot pass, several fill stations and cap, each with bugs. Compound narrow bevels are cut on site. It must keep pace with automated UT.",
      facts: [["Throughput", "Hundreds of welds/day on large diameter"], ["Paired with", "AUT"]],
      ex: "Market examples: CRC-Evans, Serimax",
    },
    {
      id: "auto_robot", layer: "automation", name: "Industrial robot cells", mode: "robot",
      sum: "A 6-axis arm with positioners, fixtures and safety fencing. Seam tracking, touch sensing and offline programming.",
      how: "Built for volume: automotive, yellow goods, trailers. The welding package (power source, torch, wire feeder, drums) is selected by the integrator or OEM. Arc data feeds quality monitoring.",
      facts: [["Arc-on time", "60–85%"], ["Capex", "High (cell + fixtures)"]],
      ex: "Robot makers: FANUC, Yaskawa, ABB, KUKA, Panasonic, OTC Daihen",
    },
    {
      id: "auto_cobot", layer: "automation", name: "Collaborative robots (cobots)", mode: "robot",
      sum: "Lightweight arms taught by hand and tablet, often without fencing. Brings automation to high-mix, low-volume shops. MIG first, TIG growing.",
      how: "The welder moves the torch to points, sets parameters in an app and presses start. Carts and tables make it portable. Payback comes from freeing scarce welders and gaining arc-on time on repeat parts.",
      facts: [["Arc-on time", "40–70%"], ["Capex", "Low–medium"], ["Adoption", "Fastest-growing automation category"]],
      ex: "ESAB cobot welding packages; arms from Universal Robots, FANUC CRX, Yaskawa, Doosan",
    },
    {
      id: "auto_special", layer: "automation", name: "Special-purpose machines", mode: "mech",
      sum: "Dedicated automation: seamers, circ welders, cladding stations, boiler panel welders, pipe mill heads and friction-stir machines.",
      how: "Built around one part family for maximum throughput. Often custom-engineered with the welding OEM.",
      facts: [["Capex", "Medium–very high"], ["Flexibility", "Low"]],
    },
    {
      id: "auto_tank", layer: "automation", name: "Tank girth & electrogas welders", mode: "mech",
      sum: "Machines that ride the tank shell: SAW girth welders for horizontal seams, electrogas climbers for vertical seams.",
      how: "Field-erected tank contractors run these to weld shells course by course, often inside and outside at once.",
      facts: [["Process", "SAW (girth), EGW (vertical)"], ["Segment", "Tanks, LNG"]],
    },

    /* =========================== FILLERS =========================== */
    {
      id: "fil_cell", layer: "filler", name: "Cellulosic electrodes",
      sum: "E6010 / E7010-P1 / E8010-P1. Deep-penetrating, fast-freeze rods for vertical-down pipeline welding.",
      how: "The cellulose coating burns to a hydrogen-rich gas that gives a digging arc. High hydrogen limits use on high-strength steels unless procedures control it.",
      facts: [["Spec", "AWS A5.1 / A5.5"], ["Where", "Pipeline stovepipe, chilled-water roots, field"]],
    },
    {
      id: "fil_lowh", layer: "filler", name: "Low-hydrogen electrodes",
      sum: "E7018, E7018-1, E8018-C1, E9018-B3. The structural and pressure-work standard. Needs rod ovens.",
      how: "A basic (lime-fluoride) coating keeps diffusible hydrogen low to prevent cracking in thick or high-strength steel. Stored in ovens once opened, or supplied in vacuum packs.",
      facts: [["Spec", "AWS A5.1 / A5.5"], ["Where", "Structural, vessels, pipe fill, repair"]],
      ex: "ESAB: Atom Arc 7018, OK 48.00",
    },
    {
      id: "fil_rutile", layer: "filler", name: "Rutile & alloy electrodes",
      sum: "E6013 general purpose, plus stainless (E308L-16) and nickel (ENiCrFe-3) rods for repair and dissimilar joints.",
      how: "Rutile coatings give easy arc striking and a smooth bead. Common in maintenance, light fabrication and emerging markets.",
      facts: [["Where", "MRO, light fab, dissimilar metals"]],
    },
    {
      id: "fil_solid_cs", layer: "filler", name: "Solid wire: carbon & low alloy",
      sum: "ER70S-6 / ER70S-3 / ER80S-Ni1. The highest-tonnage filler in the world, sold on spools, drums and bulk packs.",
      how: "A copper-coated or bare wire with deoxidizers (Mn, Si). Drums of 250–450 kg feed robots for days without changeover. Feedability and cast/helix consistency are what buyers judge.",
      facts: [["Spec", "AWS A5.18 / A5.28"], ["Share", "~40–50% of global filler tonnage"], ["Packaging", "Spools, drums, bulk"]],
      ex: "ESAB: OK Autrod, Marathon Pac drums",
    },
    {
      id: "fil_solid_ss", layer: "filler", name: "Solid wire: stainless",
      sum: "ER308LSi, ER316LSi, ER309LSi, ER2209 duplex; ferritic 409/439 grades for exhaust.",
      how: "Matched to the base metal for corrosion resistance. Used with pulsed GMAW and Ar/CO2 2% gas. 309L for dissimilar joints and cladding.",
      facts: [["Spec", "AWS A5.9"]],
    },
    {
      id: "fil_al", layer: "filler", name: "Aluminum wire",
      sum: "ER4043 (Si), ER5356 / ER5183 (Mg), ER4943. Soft wire that needs push-pull or spool guns.",
      how: "5xxx wires give strength (marine, structural). 4xxx wires give crack resistance and fluidity. Cleanliness and feeding are the main issues.",
      facts: [["Spec", "AWS A5.10"]],
    },
    {
      id: "fil_mcw", layer: "filler", name: "Metal-cored wire",
      sum: "E70C-6M. A tube filled with metal powder: higher deposition than solid wire, minimal slag, excellent gap bridging and good on galvanized steel.",
      how: "The current flows through the sheath, so the arc is wide and fast. Favored in robot cells (yellow goods, chassis, trailers). Stainless metal-cored grades are common in exhaust.",
      facts: [["Spec", "AWS A5.18 (E70C) / A5.28"], ["Where", "Robot cells, heavy equipment, exhaust"]],
      ex: "ESAB: Coreweld, OK Tubrod metal-cored",
    },
    {
      id: "fil_fcawg", layer: "filler", name: "Flux-cored wire: gas-shielded",
      sum: "E71T-1C/M (rutile, all-position), E71T-9, E71T-5 (basic, low hydrogen), E81T1-Ni1 (toughness).",
      how: "The shipbuilding and offshore workhorse. Rutile slag makes vertical-up at high current easy. Basic types serve crack-sensitive, high-restraint joints.",
      facts: [["Spec", "AWS A5.20 / A5.29 / A5.36"], ["Where", "Shipyards, offshore, heavy fab, structural shop"]],
      ex: "ESAB: Dual Shield, OK Tubrod",
    },
    {
      id: "fil_fcaws", layer: "filler", name: "Flux-cored wire: self-shielded",
      sum: "E71T-8 (seismic), E70T-4 (high deposition, flat), E71T-11 (general), E71T8-Ni1 (pipeline fill and cap).",
      how: "No gas needed: the field choice for structural erection and some pipeline and repair work.",
      facts: [["Spec", "AWS A5.20 / A5.29"], ["Where", "Field structural, pipeline, repair"]],
      ex: "ESAB: Coreshield",
    },
    {
      id: "fil_tig", layer: "filler", name: "TIG rods & precision wire",
      sum: "ER70S-2 (roots), ER80S-B2 / ER90S-B9 (Cr-Mo, P91), ER308L / 316L, ER2209, titanium, as cut lengths or spooled wire for orbital and automated TIG.",
      how: "Low tonnage but high value per kilo. Chemistry and cleanliness are tightly controlled, especially for nuclear and power.",
      facts: [["Spec", "AWS A5.18 / A5.28 / A5.9"]],
      ex: "ESAB: OK Tigrod",
    },
    {
      id: "fil_saw", layer: "filler", name: "SAW wire + flux",
      sum: "Wires EM12K, EA2 (Mo), EH14 with agglomerated basic, neutral or fused fluxes. Flux use is roughly equal to wire use by weight.",
      how: "The wire-flux pair sets the weld metal properties, so they are qualified together. Basic agglomerated fluxes give high toughness for offshore and wind. Sold in drums and bulk bags, with flux recovery systems.",
      facts: [["Spec", "AWS A5.17 / A5.23"], ["Where", "Wind, vessels, pipe mills, shipyards, beams"]],
      ex: "ESAB: OK Autrod SAW wires, OK Flux",
    },
    {
      id: "fil_strip", layer: "filler", name: "Strip electrodes + flux",
      sum: "Stainless (309L, 347) and nickel-alloy strips, 30–120 mm wide, for electroslag or SAW strip cladding.",
      how: "Covers large vessel areas with a corrosion-resistant layer in one or two passes with low dilution.",
      facts: [["Where", "Hydroprocessing reactors, heat exchangers, valves"]],
      ex: "ESAB: OK Band strips",
    },
    {
      id: "fil_ni", layer: "filler", name: "Nickel-base alloys",
      sum: "ERNiCrMo-3 (625), ERNiCr-3 (82), ERNiCrFe-7A (52M), ENiCrMo-6 (9% Ni). Many times the price of carbon-steel wire.",
      how: "Used for corrosion-resistant overlays, dissimilar metal welds (nuclear, power), LNG 9% nickel tanks and high-temperature service.",
      facts: [["Spec", "AWS A5.11 / A5.14"], ["Where", "LNG, nuclear, cladding, chemical"]],
    },
    {
      id: "fil_hard", layer: "filler", name: "Hardfacing wires & electrodes",
      sum: "Chromium carbide, complex carbide, tungsten carbide and martensitic build-up alloys as open-arc cored wire, SAW wire or stick.",
      how: "Chosen by wear mechanism (abrasion, impact, heat). Sold on service-life improvement rather than price per kilo.",
      facts: [["Where", "Mining, cement, steel mills, dredging, agriculture"]],
      ex: "ESAB: Stoody",
    },
    {
      id: "fil_none", layer: "filler", name: "Autogenous (no filler)",
      sum: "No filler metal: orbital tube welding, RSW, FSW, laser and keyhole plasma. Value sits in equipment, gas, tungsten and parts.",
      how: "Square-butt joints are fused directly. Joint prep and purge quality become critical.",
      facts: [["Where", "Semiconductor UHP, sanitary, automotive, EV"]],
    },

    /* ============================= NDT ============================= */
    {
      id: "ndt_vt", layer: "ndt", name: "VT: Visual testing & borescope",
      sum: "The first and most frequent inspection: eyes, gauges, lighting, and videoscopes for inside tube and pipe.",
      how: "The inspector (often a CWI) checks size, profile, undercut, porosity, cracks and misalignment against the code. Borescopes check root beads and heat tint inside UHP and sanitary tube. Inline laser profilers automate visual checks in robot lines.",
      facts: [["Detects", "Surface flaws, geometry, discoloration"], ["When", "During and after every weld"], ["Codes", "AWS D1.1 visual criteria, ASME BPE color charts"]],
      ex: "Videoscopes: Evident IPLEX, Waygate Technologies",
    },
    {
      id: "ndt_pt", layer: "ndt", name: "PT: Liquid penetrant",
      sum: "Dye soaks into surface-breaking cracks and a developer draws it out. For non-magnetic metals: stainless, aluminum, nickel, overlays.",
      how: "Clean → apply penetrant → dwell → remove excess → apply developer → inspect (visible or fluorescent under UV).",
      facts: [["Detects", "Surface-breaking only"], ["Cost", "Very low"], ["Codes", "ASME V Art. 6, ISO 3452"]],
      ex: "Consumables: Magnaflux",
    },
    {
      id: "ndt_mt", layer: "ndt", name: "MT: Magnetic particle",
      sum: "Magnetize ferritic steel and iron particles gather at surface and near-surface cracks. Fast and cheap for structural and heavy fab.",
      how: "An AC or DC yoke (or prods) creates the field. Wet, dry or fluorescent particles show where flux leaks at a crack. Common on fillet welds, back-gouged roots and fatigue-critical details.",
      facts: [["Detects", "Surface and slightly subsurface"], ["Materials", "Ferromagnetic only"], ["Codes", "ASME V Art. 7, ISO 17638"]],
      ex: "Yokes: Parker Research, Magnaflux",
    },
    {
      id: "ndt_rt", layer: "ndt", name: "RT: Radiography (film, CR, DR, CT)",
      sum: "X-ray or gamma rays through the weld onto film or a digital detector. A permanent image of volumetric flaws.",
      how: "Ir-192, Se-75 or X-ray tubes expose film, phosphor plates (CR) or flat panels (DR). Pipelines use internal crawlers. Radiation exclusion zones stop nearby work, which is the main reason PAUT is replacing RT. CT scans cast and battery parts.",
      facts: [["Detects", "Porosity, slag, incomplete penetration"], ["Weak on", "Tight planar cracks and lack of fusion at some angles"], ["Codes", "ASME V Art. 2, API 1104, ISO 17636"]],
      ex: "Equipment: Waygate Technologies, Comet Yxlon",
    },
    {
      id: "ndt_ut", layer: "ndt", name: "UT: Conventional ultrasonic",
      sum: "A single-element probe sends sound into the weld and reads echoes: angle-beam for weld flaws, straight-beam for laminations and thickness.",
      how: "A portable flaw detector shows an A-scan. The technician scans the probe by hand with couplant and sizes reflectors by amplitude against a reference. Thickness gauges map corrosion in service. Standard for structural CJP welds under AWS D1.1.",
      facts: [["Detects", "Volumetric and planar flaws (cracks, lack of fusion)"], ["Record", "Manual, limited"], ["Codes", "AWS D1.1 Clause 8, ASME V Art. 4/5, ISO 17640"]],
      ex: "Flaw detectors: Evident EPOCH, Waygate USM, Sonatest",
    },
    {
      id: "ndt_paut", layer: "ndt", name: "PAUT: Phased array UT",
      sum: "A probe with many elements steers and focuses the beam electronically. Encoded scans give a permanent image. The main replacement for RT on thick welds.",
      how: "Sectorial and linear scans sweep the weld volume from one probe position. A wheel encoder on a scanner records C-scans and S-scans that can be audited later. No radiation, so fabrication continues next to inspection. Accepted in lieu of RT under ASME and AWS rules with qualified procedures.",
      facts: [["Detects", "Volumetric and planar, with sizing"], ["Where", "Wind towers, vessels, pipe spools, structural, pipelines"], ["Codes", "ASME V Art. 4, ASME CC 2235, ISO 13588"]],
      ex: "Instruments: Evident OmniScan, Eddyfi Gekko / Mantis, Sonatest Veo, Zetec TOPAZ",
    },
    {
      id: "ndt_tofd", layer: "ndt", name: "TOFD: Time-of-flight diffraction",
      sum: "Two probes straddle the weld and time the diffracted signals from crack tips. Very accurate through-wall sizing, and fast.",
      how: "Usually run together with PAUT, because TOFD has dead zones near the surfaces. Strong on heavy wall: vessels, wind towers, monopiles.",
      facts: [["Strength", "Height sizing of cracks"], ["Codes", "ASME V Art. 4 App., ISO 10863"]],
    },
    {
      id: "ndt_aut", layer: "ndt", name: "AUT: Automated UT (pipeline)",
      sum: "Multi-probe or phased-array band scanners that inspect a full girth weld in minutes, with zones mapped to the bevel.",
      how: "Zonal discrimination divides the weld into slices matched to the narrow mechanized bevel. Results come back before the next weld is made, so problems in the spread are fixed quickly. Acceptance is often based on engineering critical assessment (ECA).",
      facts: [["Throughput", "Keeps pace with mechanized spreads"], ["Codes", "API 1104, DNV-ST-F101, ASTM E1961"]],
      ex: "Service providers: Applus+ RTD Rotoscan, Mistras and others",
    },
    {
      id: "ndt_et", layer: "ndt", name: "ET / ECA: Eddy current (welds)",
      sum: "A coil induces eddy currents in the metal, and cracks disturb them. Finds surface-breaking weld cracks through paint and coatings, mostly in service.",
      how: "Weld-specific probes (or eddy current arrays for C-scan imaging) are scanned along the toe of the weld without removing coatings or couplant. That makes ET ideal for fatigue crack checks on offshore structures, bridges, cranes, rail and wind towers in service. Also used for ferrite and coating-thickness measurement and in aerospace.",
      facts: [["Detects", "Surface and near-surface cracks"], ["Strength", "Works through coatings, fast, no couplant"], ["Limits", "Not volumetric; conductive metals only"], ["Codes", "ASME V Art. 8, ISO 17643"]],
      ex: "Instruments: Eddyfi (Reddy, Ectane), Evident NORTEC",
    },
    {
      id: "ndt_ettube", layer: "ndt", name: "Tube ET: bobbin, RFT, NFT",
      sum: "Probes pulled through heat exchanger, condenser and boiler tubes to find wall loss and cracks during outages.",
      how: "Bobbin coils for non-ferrous tubes; remote-field (RFT) and near-field (NFT) testing for carbon-steel tubes; IRIS (rotating UT) to confirm. Pairs with the tube-to-tubesheet application.",
      facts: [["When", "In-service, shutdowns and outages"], ["Where", "Refinery exchangers, power condensers, boilers, HVAC chillers"]],
      ex: "Instruments: Eddyfi, Zetec",
    },
    {
      id: "ndt_leak", layer: "ndt", name: "Leak testing (He, pressure, vacuum box)",
      sum: "Proves the system is tight: helium mass spectrometry for UHP and battery trays, pressure decay, hydrotest, and vacuum-box tests on tank floors.",
      how: "The final functional check for fluid and gas systems. Helium detection reaches very low leak rates, which UHP semiconductor systems require.",
      facts: [["Where", "Semiconductor, pharma, EV trays, tanks, liquid cooling"]],
      ex: "Helium detectors: INFICON, Pfeiffer Vacuum",
    },
    {
      id: "ndt_monitor", layer: "ndt", name: "In-process weld monitoring (digital QA)",
      sum: "Current, voltage, wire feed, gas and travel logged for every weld and checked against the WPS. Controls quality during welding instead of only inspecting after.",
      how: "Connected power sources stream arc data to software that flags out-of-window welds, tracks consumable use and builds traceability records. Seam tracking and laser vision add geometry checks. The strategic pitch: fewer escapes, less destructive sampling, proof of compliance.",
      facts: [["Where", "Robot cells, orbital logs, pipelines, high-spec fab"]],
      ex: "ESAB: WeldCloud",
    },
  ],

  /* ====================== MARKET STRUCTURE ====================== */
  groups: [
    { id: "energy", name: "Energy & Power", sum: "Moving and generating energy: pipelines, power plants, wind, LNG and hydrogen." },
    { id: "process", name: "Process & Pressure Equipment", sum: "Plants and the code-stamped vessels, piping and tanks inside them." },
    { id: "infra", name: "Infrastructure & Construction", sum: "Buildings, bridges and the data centers driving new construction." },
    { id: "transport", name: "Transportation & Defense", sum: "Things that move: cars, rail, trucks, ships, aircraft and military vehicles." },
    { id: "mfg", name: "Industrial Manufacturing", sum: "Factory-built products: job shops, heavy equipment, HVAC and appliances." },
    { id: "purity", name: "High-Purity & Hygienic", sum: "Clean systems where weld cleanliness is the product: fabs, pharma, food." },
    { id: "mro", name: "Mining & Maintenance", sum: "Keeping heavy assets running: repair, rebuild and wear protection." },
  ],
  // group, typical buyers and route to market for each segment
  segmentMeta: {
    seg_pipeline: { group: "energy", buyers: "Pipeline contractors, pipe mills, owner-operators", channel: "Direct to contractors; rental fleets" },
    seg_power: { group: "energy", buyers: "Boiler and HRSG OEMs, nuclear fabricators, utilities, EPCs", channel: "Direct, specification-driven" },
    seg_wind: { group: "energy", buyers: "Tower and monopile factories", channel: "Direct key accounts" },
    seg_lng: { group: "energy", buyers: "EPCs, tank contractors, cryogenic equipment makers", channel: "Direct, project-based" },
    seg_process: { group: "process", buyers: "EPC contractors, pipe fabricators, owner-operators (turnarounds)", channel: "Direct and distribution; EPC specifications decide" },
    seg_pv: { group: "process", buyers: "Vessel and tank fabricators, tank erection contractors", channel: "Direct and distribution" },
    seg_struct: { group: "infra", buyers: "Steel fabricators, erectors, bridge fabricators", channel: "Distribution; direct for large fabricators" },
    seg_dc: { group: "infra", buyers: "Mechanical contractors, steel erectors, modular prefab shops, electrical equipment OEMs", channel: "Distribution and contractor accounts; hyperscaler specs influence choices" },
    seg_auto: { group: "transport", buyers: "Vehicle OEMs, Tier 1 and Tier 2 suppliers, robot integrators", channel: "Direct key accounts and integrators" },
    seg_transport: { group: "transport", buyers: "Railcar builders, truck and trailer OEMs, bus makers", channel: "Direct and distribution" },
    seg_ship: { group: "transport", buyers: "Naval and commercial shipyards, offshore yards", channel: "Direct, project-based" },
    seg_aero: { group: "transport", buyers: "Engine and airframe OEMs, MRO shops, defense primes", channel: "Direct; qualified supplier lists" },
    seg_genfab: { group: "mfg", buyers: "Job shops, contract fabricators, OEM fab shops", channel: "Distribution (welding supply stores)" },
    seg_yellow: { group: "mfg", buyers: "Equipment OEMs (e.g. Caterpillar, Deere, Komatsu, Volvo CE) and their Tier 1 fabricators", channel: "Direct key accounts and integrators" },
    seg_hvac: { group: "mfg", buyers: "HVAC and appliance OEMs, compressor makers", channel: "Direct and integrators" },
    seg_semi: { group: "purity", buyers: "Specialty gas-system and process piping contractors", channel: "Specialist distribution and direct" },
    seg_food: { group: "purity", buyers: "Sanitary fabricators, process equipment OEMs", channel: "Distribution" },
    seg_mining: { group: "mro", buyers: "Mines, cement and steel plants, repair and hardfacing shops", channel: "Distribution and service" },
  },
};
