/*
 * EBXWorld: Gemba walk content
 * ------------------------------------------------------------------
 * One entry per customer site. Stops are listed in walking order and
 * their ids must match the camera stops in gemba-world.js.
 *
 * Stop fields:
 *   see      what you would see standing there
 *   people   "Role: what they care about"
 *   pains    waste and pain points you would notice
 *   products welding products in use at this stop
 *   ask      questions to ask on a real visit
 *   play     where ESAB can win (strategy note)
 *   links    node ids from data.js (open as definitions)
 *
 * Headcounts, rates and volumes are indicative. Validate them with
 * field sales before external use.
 */
window.GEMBA = {
  sites: [
    /* ============================ WIND ============================ */
    {
      id: "wind", name: "Wind tower factory", segment: "seg_wind", apps: ["app_windtower", "app_monopile"], tier: "Heavy",
      sum: "A flow-line factory that turns steel plate into 20–30 m tower sections. Its heartbeat is submerged-arc welding: long seams inside and outside each rolled can, then circumferential seams that join cans into sections on turning rolls.",
      facts: [
        ["Output", "Several hundred sections a year at a large plant (indicative)"],
        ["Plate", "S355, 20–80 mm thick, 3–5 m wide"],
        ["Section", "4–8 m diameter, 20–30 m long, 50–100+ t"],
        ["Shifts", "2–3 shifts, 5–7 days"],
        ["Weld metal", "Roughly 1–2% of steel weight: several tonnes per tower (indicative)"],
        ["Main processes", "Tandem and twin SAW; MIG/FCAW for tacks, flanges and internals"],
      ],
      economics: "Cost per tonne of tower drives everything. After steel, welding hours and the weld repair rate are the biggest costs the plant controls. One repair on a circumferential seam can hold up a whole bay.",
      before: "PPE: boots, helmet, glasses, hi-vis, hearing protection. Stay out of crane lift paths and never walk under a suspended can. Ask before taking photos.",
      stops: [
        {
          id: "plate", name: "Plate yard & bevel cutting",
          see: "Stacks of heavy plate under magnet cranes. CNC cutting machines with oxy-fuel or plasma bevel heads cut each plate to its developed shape (the plates for tapered cones have curved edges) and prepare the weld bevel in one pass. You smell primer smoke and hear the hiss of the torches.",
          people: ["Crane operator: plate availability and safe lifts", "Cutting operator: bevel angle and root face within tolerance", "Production planner: plates in the right order for the cone sequence"],
          pains: ["Bevel errors show up later as SAW defects and repairs", "Cranes are the bottleneck, so welding bays wait for plate", "Wear on cutting consumables (nozzles, electrodes, shields)"],
          products: ["Plasma and oxy-fuel cutting systems with bevel heads", "Cutting consumables", "Gas regulators and manifolds"],
          ask: ["How many plates a shift, and what is your bevel rework rate?", "Plasma or oxy-fuel on thick plate? Why?", "Who owns bevel quality: cutting or welding?"],
          play: "Cutting is an ESAB strength alongside welding. Bevel quality directly drives SAW repair rates, so one joint-quality story covering cutting and welding is credible here.",
          links: [],
        },
        {
          id: "roll", name: "Rolling & tacking cans",
          see: "A 4-roll plate bending machine curls each plate into a can, a ring 2–4 m long. The long seam is closed and tacked with MIG or flux-cored wire. Run-on and run-off tabs are welded at the seam ends so the SAW arc starts and stops off the part.",
          people: ["Roll operator: roundness and edge alignment (hi-lo)", "Tack welder: tacks strong enough to survive rolling and handling"],
          pains: ["Poor roundness or edge mismatch causes lack of fusion later", "Tacks crack during handling", "Waiting on the roll, the most expensive machine in the line"],
          products: ["Semi-automatic MIG/FCAW power sources and guns", "Solid or flux-cored wire (ER70S-6, E71T-1)"],
          ask: ["What causes most of your long-seam repairs?", "Do the tacks get remelted by the SAW or ground out?"],
          play: "Tacking is small volume but touches every can. A reliable semi-auto package and wire on the same contract as the SAW business keeps competitors out of the plant.",
          links: ["proc_gmaw", "proc_fcawg", "auto_semi"],
        },
        {
          id: "longseam", name: "Long-seam SAW (inside & outside)",
          see: "A column & boom reaches inside the can to weld the inside of the long seam with tandem SAW. The can is then turned, the root back-gouged, and the outside welded. Flux feeds from a hopper and is vacuumed back for reuse. The arc is hidden under the flux: you see glowing slag peeling off behind the head.",
          people: ["SAW operator: watches the seam tracker and wire and flux levels, often runs 2–3 machines", "Welding engineer: heat input, WPS compliance, toughness at −40 °C for offshore", "Maintenance: contact tips, flux recovery, drive rolls"],
          pains: ["Damp or contaminated flux causes porosity and hydrogen cracking", "Stops for wire or flux changes leave start/stop defects", "Back-gouging with carbon arc is slow, noisy and dirty"],
          products: ["Column & boom with twin or tandem SAW heads", "SAW wire (EM12K, EA2) and agglomerated basic flux in bulk", "Flux recovery and drying equipment", "Carbon arc gouging"],
          ask: ["What deposition rate do you run per head? Could a cold-wire addition raise it?", "How do you store and re-dry flux?", "Wire in drums or coils, and how often do you stop to change it?"],
          play: "This is the biggest consumables pull in the plant. Wire and flux are qualified together into the WPS, so once specified the pair is sticky. ESAB can sell the whole chain: column & boom, heads, ICE cold-wire technology, flux, wire, bulk packs and Arcair gouging.",
          links: ["proc_saw", "auto_cab", "fil_saw"],
        },
        {
          id: "circ", name: "Circumferential seams on turning rolls",
          see: "A line of cans sits on turning rolls. Column & booms weld the seam between each pair of cans while the section turns slowly under the head. Finished sections grow to 20–30 m. This is the longest bay in the plant.",
          people: ["SAW operator", "Rigging crew moving 50–100 t sections", "Quality inspector checking fit-up before welding"],
          pains: ["Rotator drift makes the section walk off the rolls", "Fit-up (gap, misalignment) sets weld volume and defect rate", "One repair can block the bay for hours"],
          products: ["Anti-drift turning rolls", "Column & boom with seam tracking and cameras", "SAW wire and flux"],
          ask: ["What limits bay throughput: welding speed, fit-up or cranes?", "How do you control heat input and interpass temperature on thick seams?"],
          play: "Productivity tools (seam tracking, anti-drift rolls, multi-wire heads) sell on hours saved per section. Bring a before-and-after welding-time calculation.",
          links: ["auto_positioner", "auto_cab", "proc_saw"],
        },
        {
          id: "flange", name: "Flange fit-up & welding",
          see: "Heavy forged flanges are welded to the ends of each section. Flatness after welding is critical for bolting the tower together, so welders follow a careful balanced sequence, with SAW or multi-pass MIG/FCAW.",
          people: ["Welder or operator", "Quality: flange flatness and ovality checks"],
          pains: ["Distortion pulls flanges out of flat", "Long multi-pass welds on thick sections", "Rework when flatness fails"],
          products: ["SAW or MIG/FCAW on positioners", "Flux-cored wire for out-of-position passes"],
          ask: ["How do you control flange distortion?", "Would a narrower groove or a higher-deposition process cut the number of passes?"],
          play: "Engineering support (weld sequence, groove design) is valued here and sets a supplier apart from a catalog.",
          links: ["fil_fcawg"],
        },
        {
          id: "ndt", name: "UT / PAUT inspection & repair",
          see: "Every seam is inspected. A technician drives an encoded phased-array and TOFD scanner along the weld on a magnetic crawler, and the results appear as images on a laptop. Defects are marked, gouged out and re-welded.",
          people: ["NDT Level II/III technician: detecting and sizing flaws", "Welding QA: tracks the repair rate", "Customer or third-party inspector"],
          pains: ["The repair rate is the plant's report card", "Waiting for inspection holds sections in the bay", "Repairs on thick welds need preheat and approved repair procedures"],
          products: ["PAUT/TOFD instruments and scanners", "Carbon arc gouging for repairs", "Low-hydrogen electrodes or flux-cored wire for repairs"],
          ask: ["What is your repair rate per metre of weld, and the top three defect types?", "Is inspection on the critical path?"],
          play: "Repair data is the best door-opener. Link defect types (porosity, lack of fusion, slag) to flux handling, fit-up and parameters, then offer to bring the rate down.",
          links: ["ndt_paut", "ndt_tofd", "ndt_ut"],
        },
        {
          id: "paint", name: "Blast, paint & internals",
          see: "Sections are grit-blasted and painted, then fitted with door frames, platforms and cable ladders, mostly MIG welded. They ship on multi-axle trailers or barges.",
          people: ["Paint shop supervisor", "Outfitting welders"],
          pains: ["Spatter and slag left on the steel cause coating defects", "Welding internals after painting damages the coating"],
          products: ["Semi-auto MIG for internals", "Low-spatter pulse waveforms"],
          ask: ["How much time goes into grinding spatter before blasting?"],
          play: "Low-spatter pulse processes cut grinding before painting, which is an easy ROI story.",
          links: ["proc_gmaw"],
        },
      ],
    },

    /* ========================= DATA CENTER ========================= */
    {
      id: "dc", name: "Data center campus + prefab shop", segment: "seg_dc", apps: ["app_chw", "app_dcstruct", "app_liquid", "app_skid", "app_enclosure"], tier: "Heavy + Light",
      sum: "A hyperscale campus is a construction site racing a power-on date, fed by off-site shops that prefabricate piping, skids and electrical rooms. Most of the welding is done by subcontractors: steel erectors, mechanical contractors and prefab fabricators.",
      facts: [
        ["Scale", "Several data halls; 100 MW+ campuses are common (indicative)"],
        ["Schedule", "~18–30 months from ground-break to power-on (indicative)"],
        ["Who welds", "Steel erectors, mechanical contractors, prefab shops, equipment OEMs"],
        ["Main processes", "FCAW-S and stick in the field; MIG, FCAW-G and orbital TIG in prefab"],
        ["Constraints", "Hot-work permits, labor shortage, speed"],
      ],
      economics: "Speed to power is worth more than almost anything else. Contractors pay for productivity and for moving hours off site. Skilled labor is scarce, so prefabrication and mechanical joining keep growing.",
      before: "A site induction is required; full PPE. Hot-work permits apply inside buildings. Often you will visit the contractor's prefab shop rather than the site itself.",
      stops: [
        {
          id: "overview", name: "Campus overview & laydown yard",
          see: "Crawler and tower cranes over several halls at different stages. A laydown yard is full of steel beams and pipe spools waiting to be installed. Hundreds of trade workers from different contractors, and trucks arriving all day.",
          people: ["General contractor PM: schedule and cost", "Superintendent: sequencing trades and safety", "MEP coordinator: clashes between piping, ducts and cable trays"],
          pains: ["Trades stacked on top of each other", "Material staging and double handling", "Labor shortage across every trade"],
          products: ["Engine-driven multiprocess welders, often from rental fleets", "Portable wire feeders"],
          ask: ["Which contractors do the welding here?", "Where is the prefabrication done?", "Who specifies welding equipment and consumables: contractor, GC or owner?"],
          play: "Map the influencers. The GC rarely buys welding; the steel and mechanical contractors do, often through distributors and rental fleets. Hyperscaler design standards can pull a spec across many sites.",
          links: [],
        },
        {
          id: "steel", name: "Structural steel erection",
          see: "Ironworkers on boom lifts at column splices and moment connections, welding with self-shielded flux-cored wire from feeders powered by engine drives parked below. A special inspector follows with UT.",
          people: ["Ironworker welder: comfort, reliable arc starts in wind", "Erection foreman: crane time and pieces per day", "Special inspector: UT on complete-joint-penetration welds"],
          pains: ["Wind, rain and working at height", "UT rejects on field welds", "Waiting for special inspection before the next level"],
          products: ["Engine-driven welders and portable feeders", "E71T-8 self-shielded wire (seismic demand-critical)", "E7018 electrodes"],
          ask: ["Flux-cored or stick for field connections?", "What is your UT reject rate?", "Do you rent or own your welding machines?"],
          play: "Rugged portable packages and demand-critical FCAW-S wire, plus partnerships with rental fleets that supply the machines.",
          links: ["app_dcstruct", "proc_fcaws", "fil_fcaws"],
        },
        {
          id: "plant", name: "Central plant & chilled-water piping",
          see: "Chillers, pumps and huge chilled-water headers (24–48 in) on supports. Pipefitter-welders make field tie-ins with a TIG or stick root and a stick or flux-cored fill; smaller lines use grooved mechanical couplings.",
          people: ["Pipefitter-welder: certifications, fit-up", "Mechanical foreman: joints per day", "QA: sample RT or PAUT"],
          pains: ["Field welds are slower and riskier than shop welds", "Weather and position", "Welder certifications and availability"],
          products: ["Stick electrodes (E6010 / E7018), TIG and FCAW", "Pipe bevelling and facing tools", "Engine-driven welders"],
          ask: ["What share of welds is done in the field vs the shop?", "Why grooved rather than welded on this line size?"],
          play: "Push welding into the shop with spools, positioners and faster processes, and compete with grooved couplings on large bore, where welding still wins.",
          links: ["app_chw", "proc_smaw", "fil_cell"],
        },
        {
          id: "hall", name: "Data hall & liquid cooling",
          see: "White space with rows of racks, overhead cable trays and stainless TCS loops feeding cooling distribution units (CDUs). Welding inside the hall needs hot-work permits and a fire watch, so most joints arrive pre-welded or use press-fit. When they are welded, it is orbital TIG with an argon purge.",
          people: ["Mechanical contractor: leak-free, clean loops", "Commissioning agent: flushing and pressure tests", "Owner's representative: risk near IT equipment"],
          pains: ["Hot-work restrictions and fire watch", "Particle cleanliness of the coolant", "Leak risk next to live IT", "Schedule compression at the end of the job"],
          products: ["Orbital GTAW systems (enclosed and open heads)", "Stainless filler, tungsten, purge equipment", "Borescopes and leak testing"],
          ask: ["How are TCS loops joined: orbital, press-fit or grooved?", "What is the cleanliness spec, and who checks it?"],
          play: "Orbital TIG for manifolds and CDU loops, welded in prefab, is the growth niche. Sell it with weld logs and documentation that commissioning teams need.",
          links: ["app_liquid", "auto_orbtube", "ndt_leak"],
        },
        {
          id: "power", name: "Generator & electrical yard",
          see: "Rows of diesel or gas gensets, fuel tanks, transformers and prefabricated e-houses delivered by truck. Little welding happens here, mainly supports and fuel piping.",
          people: ["Electrical contractor", "Commissioning team"],
          pains: ["Long lead times for gensets, switchgear and transformers"],
          products: ["MIG and TIG in the OEM factories that build the equipment"],
          ask: ["Which OEMs build this equipment, and where are their factories?"],
          play: "The weld volume sits upstream at switchgear, genset and transformer OEMs. Follow the equipment back to the factory.",
          links: ["app_enclosure", "app_skid"],
        },
        {
          id: "prefab", name: "Off-site prefab shop",
          see: "A warehouse where pipe spools turn on positioners under semi-auto MIG and flux-cored guns, an orbital TIG station welds stainless loops, a cobot welds skid base frames, and finished modules leave on flatbed trucks.",
          people: ["Shop superintendent: spools per day", "Welders and fitters", "QC: weld maps and documentation", "Logistics: shipping in installation sequence"],
          pains: ["Throughput per welder", "Paperwork for every weld", "Shipping in the order the site needs"],
          products: ["Positioners, pulse MIG, FCAW, orbital TIG, cobots", "Weld data software for traceability"],
          ask: ["How many spool welds per welder per day?", "Do you track welds in software?", "Plans for more automation?"],
          play: "The best place for ESAB: a fast-growing factory that buys productivity equipment, consumables and weld data together.",
          links: ["app_skid", "auto_positioner", "auto_cobot"],
        },
        {
          id: "qa", name: "QA, hydrotest & commissioning",
          see: "Pressure tests with test pumps and gauges, flushing rigs, sample RT or PAUT, and binders (or tablets) of turnover documentation.",
          people: ["QA manager", "Commissioning agent"],
          pains: ["A failed hydrotest means cutting out welds", "Documentation turnover delays"],
          products: ["Weld data and traceability software", "Leak-testing equipment"],
          ask: ["What fails most often in testing?"],
          play: "Traceable weld data shortens turnover packs and supports quality claims.",
          links: ["ndt_rt", "ndt_leak"],
        },
      ],
    },

    /* ========================== JOB SHOP ========================== */
    {
      id: "jobshop", name: "Job shop with a cobot", segment: "seg_genfab", apps: ["app_jobshop", "app_enclosure"], tier: "Light",
      sum: "A 30–80 person contract fabricator making brackets, frames and weldments for local OEMs in batches of 5 to 500. Every job is different, deadlines are short, and good welders are the scarcest resource.",
      facts: [
        ["Headcount", "~30–80 people, 8–20 welders (indicative)"],
        ["Batch size", "5–500 parts"],
        ["Materials", "Mild steel 1–20 mm, some stainless and aluminum"],
        ["Main processes", "Semi-auto MIG; some TIG and flux-cored"],
        ["Buying", "Through a local distributor, often with vendor-managed inventory"],
      ],
      economics: "Shops live on quote accuracy and throughput. A cobot pays back when it frees a welder for harder work and keeps arc-on time high on repeat jobs.",
      before: "Glasses, boots and hearing protection. Don't look at an arc without a filter (welding flash). Walk the marked aisles and watch for forklifts.",
      stops: [
        {
          id: "office", name: "Front office & quoting",
          see: "An estimator with drawings on two screens, a whiteboard of jobs and due dates, and the owner, who also answers the phone.",
          people: ["Owner: cash flow, capacity, hiring", "Estimator: hours per part on the quote", "Scheduler: rush orders"],
          pains: ["Quoting weld time is guesswork", "Rush orders break the schedule", "Hiring and keeping welders"],
          products: ["Connected machines and weld data (for real weld times)"],
          ask: ["How do you estimate weld time?", "Which jobs repeat every month?"],
          play: "Repeat jobs are the cobot pipeline, and real weld-time data makes quotes more accurate.",
          links: [],
        },
        {
          id: "cut", name: "Cutting: laser & plasma",
          see: "A fiber laser cuts sheet in an enclosed machine, and a plasma table cuts thicker plate. Parts are knocked out of the skeleton and sorted onto carts.",
          people: ["Cutting operator: nesting, part sorting"],
          pains: ["Dross and bevel quality", "Sorting mixed parts", "Consumable life on plasma"],
          products: ["Plasma cutting tables and consumables"],
          ask: ["Plasma or laser for 10–20 mm plate?"],
          play: "Cutting consumables are a steady revenue stream, and clean, accurate cut parts are what make cobot welding work.",
          links: [],
        },
        {
          id: "bend", name: "Forming: press brake",
          see: "A press brake bends sheet and plate into channels and brackets. Small angle errors stack up and change the gap at the weld joint.",
          people: ["Brake operator"],
          pains: ["Part-to-part variation", "Setup time on small batches"],
          products: [],
          ask: ["What is your bend tolerance, and does it cause fit-up problems in welding?"],
          play: "Consistent parts are the precondition for automation. Ask this before selling a cobot.",
          links: [],
        },
        {
          id: "fit", name: "Fit-up & tacking",
          see: "Modular fixture tables with a hole grid, clamps and stops. Fitters tack parts together with MIG before full welding.",
          people: ["Fitter: squareness, gaps"],
          pains: ["Building fixtures takes time", "Tacks that break during handling"],
          products: ["Fixture tables and clamps", "Semi-auto MIG"],
          ask: ["Do you build dedicated fixtures or use modular tables?"],
          play: "A starter fixture kit bundled with a cobot removes a common objection.",
          links: ["auto_semi"],
        },
        {
          id: "manual", name: "Manual MIG bays",
          see: "A row of booths with red welding curtains. Welders run semi-auto MIG (pulse on the newer machines) from 15 kg spools, with gas cylinders chained to carts and fume arms over the bench.",
          people: ["Welder: gun comfort, arc feel, helmet", "Lead hand: output per shift"],
          pains: ["Arc-on time around 20–30%", "Frequent spool changes", "Fume exposure", "Staff turnover"],
          products: ["MIG power sources and guns", "Solid wire ER70S-6 on spools", "Gas regulators", "Fume extraction", "Helmets and PPE"],
          ask: ["Spools or drums?", "What do your welders complain about?"],
          play: "Welders' preference wins equipment decisions here. Guns, helmets and consumables are sticky, and the local distributor relationship matters most.",
          links: ["proc_gmaw", "fil_solid_cs", "auto_semi"],
        },
        {
          id: "cobot", name: "Cobot cell",
          see: "A cobot on a two-station table. The operator loads parts on one side while the cobot welds the other. A new part is taught in minutes by hand-guiding the torch. Wire comes from a 250 kg drum.",
          people: ["Cobot operator, often a former welder", "Owner: payback and utilization"],
          pains: ["Fixturing and part variation", "Programming time on one-off jobs", "Safety questions"],
          products: ["Cobot welding package", "Wire in drums", "Nozzle cleaning"],
          ask: ["Which parts run on the cobot, and what is its utilization?", "What stopped you automating before?"],
          play: "Open the MIG cobot cell in 3D to see each part and how the brands compare.",
          links: ["auto_cobot", "fil_mcw"], system: true,
        },
        {
          id: "finish", name: "Grind, QC & paint",
          see: "Grinding benches for spatter and weld blending, a QC table with fillet gauges, a powder-coat line, and pallets waiting to ship.",
          people: ["QC inspector", "Finisher"],
          pains: ["Grinding spatter is pure waste", "Rework found at QC"],
          products: ["Low-spatter waveforms", "Metal-cored wire"],
          ask: ["How many hours a week go into grinding?"],
          play: "Low-spatter processes and metal-cored wire cut grinding time, so show the saving in hours.",
          links: ["fil_mcw"],
        },
      ],
    },

    /* ========================== PIPELINE ========================== */
    {
      id: "pipeline", name: "Pipeline spread", segment: "seg_pipeline", apps: ["app_girth", "app_doublejoint"], tier: "Heavy",
      sum: "A factory that moves along the route, several kilometres long. Crews clear the right-of-way, string pipe, weld joints in a firing line, inspect, coat and lower the pipe into the trench.",
      facts: [
        ["Crew", "Hundreds of people spread over several km (indicative)"],
        ["Pipe", "API 5L X52–X80, 12–48 in"],
        ["Rate", "Dozens to 100+ welds a day, depending on diameter and method (indicative)"],
        ["Main processes", "Cellulosic stick (vertical-down) or mechanized GMAW; FCAW-S fill and cap on some spreads"],
        ["Codes", "API 1104, CSA Z662"],
      ],
      economics: "A spread costs a lot per day, so welds per day is the number that matters. When the firing line stops, everyone behind it waits. Weld repairs and weather are the enemies.",
      before: "Strict safety orientation. Stay clear of sidebooms and suspended pipe. Hi-vis, hard hat, FR clothing.",
      stops: [
        {
          id: "row", name: "Right-of-way & stringing",
          see: "Pipe joints 12–24 m long are trucked in and laid on wooden skids beside the trench. A bending machine cold-bends joints to follow the terrain.",
          people: ["Stringing crew", "Bending engineer"],
          pains: ["Logistics and mud", "Damage to bevels and coating in handling"],
          products: ["Bevelling machines"],
          ask: ["How many joints a day can the stringing crew supply?"],
          play: "Context stop: the welding crew can only go as fast as pipe arrives.",
          links: [],
        },
        {
          id: "lineup", name: "Line-up & root pass",
          see: "Sideboom tractors lift the next joint while an internal line-up clamp aligns it. Two to four welders run the root pass together, vertical-down with E6010 stick, and the hot pass follows within minutes. Mechanized spreads use an internal root welder instead.",
          people: ["Root welders: often paid by the day, strong opinions on electrodes", "Welding foreman", "Line-up operator"],
          pains: ["Hi-lo misalignment", "Root defects found later by inspection", "Pace: everyone waits for the root"],
          products: ["Cellulosic electrodes (E6010, E8010)", "Engine-driven welders", "Internal welding systems"],
          ask: ["Stick or mechanized on this spread?", "Which electrode brand do your welders ask for, and why?"],
          play: "Welders judge cellulosic electrodes by feel. Welder trials on the spread drive the spec more than any datasheet.",
          links: ["app_girth", "fil_cell", "proc_smaw"],
        },
        {
          id: "firing", name: "Firing line: fill & cap stations",
          see: "A row of welding tents or shacks, one per joint, each adding passes. Welding rigs (trucks carrying engine-driven welders) are parked alongside. On mechanized spreads, dual-torch GMAW bugs run on bands around the pipe inside the shacks.",
          people: ["Fill and cap welders", "Rig owners (welders often own their truck and machine)"],
          pains: ["Wind and rain, hence the tents", "Keeping every station in step", "Porosity from moisture"],
          products: ["Engine drives", "E8010 or E7018 electrodes", "E71T8-Ni1 self-shielded wire", "GMAW bugs and solid wire"],
          ask: ["How many welds a day does the firing line do?", "Who owns the welding machines: the contractor or the welders?"],
          play: "Engine-driven welders sold to welder-owners and rental fleets. Electrodes and wire are sold through contractors and distributors.",
          links: ["auto_mechpipe", "fil_fcaws", "auto_manual"],
        },
        {
          id: "aut", name: "Inspection: AUT or X-ray",
          see: "A small shack where a band scanner runs automated UT around the finished weld, or an X-ray crawler travels inside the pipe. Results arrive within minutes, and a repair crew cuts out and re-welds any rejects.",
          people: ["NDT technicians", "Repair welders"],
          pains: ["Repair rate", "Inspection has to keep pace with welding"],
          products: ["AUT and RT services", "Repair electrodes"],
          ask: ["What is the repair rate, and which defect is most common?"],
          play: "Tie consumable choice to repair-rate data. Moisture pickup in electrodes and wire is a classic cause of porosity.",
          links: ["ndt_aut", "ndt_rt"],
        },
        {
          id: "coat", name: "Field joint coating",
          see: "The bare steel at each girth weld is blasted and coated (epoxy or heat-shrink sleeves), then checked with a holiday detector for gaps in the coating.",
          people: ["Coating crew"],
          pains: ["Weather", "Coating failures near the weld"],
          products: [],
          ask: ["Does spatter or slag near the weld cause coating problems?"],
          play: "Context stop: clean welds make coating faster.",
          links: [],
        },
        {
          id: "lower", name: "Lowering-in & tie-ins",
          see: "Several sidebooms lower the welded string into the trench together. Tie-in crews then weld sections together down in the ditch, in awkward positions, mostly with stick.",
          people: ["Tie-in welders", "Sideboom operators"],
          pains: ["Confined, awkward positions", "Water in the ditch"],
          products: ["Stick electrodes", "Engine drives"],
          ask: ["How many tie-ins per day, and what is their repair rate?"],
          play: "All-position electrodes that forgive awkward access win the tie-in crews.",
          links: ["proc_smaw", "fil_lowh"],
        },
      ],
    },

    /* ========================== AEROSPACE ========================== */
    {
      id: "aero", name: "Aerospace component shop", segment: "seg_aero", apps: ["app_aero"], tier: "Light",
      sum: "A clean, controlled shop welding titanium and nickel-alloy engine and airframe parts in small batches. Every weld is traceable to a qualified welder, an approved procedure and an inspection record.",
      facts: [
        ["Materials", "Titanium, Inconel 718/625, stainless"],
        ["Batch size", "1–50 parts"],
        ["Main processes", "Manual and automated GTAW, plasma, laser, electron beam"],
        ["Quality", "AWS D17.1, Nadcap accreditation, customer specs"],
        ["Inspection", "Fluorescent penetrant, X-ray / CT, eddy current, dimensional"],
      ],
      economics: "Parts are worth thousands of dollars each and scrap is expensive, so quality and certification outweigh equipment price. Qualification makes switching suppliers slow.",
      before: "Clean-shop rules and export-controlled areas (ITAR/EAR). No photos. Gloves near cleaned parts.",
      stops: [
        {
          id: "clean", name: "Receiving & chemical clean",
          see: "Parts are degreased and chemically etched in a line of tanks. Titanium picks up contamination easily, so parts are handled with gloves and welded within a set time after cleaning.",
          people: ["Process technician"],
          pains: ["Contamination leads to porosity and brittle welds"],
          products: [],
          ask: ["What is the maximum time between cleaning and welding?"],
          play: "Context stop: cleanliness rules everything downstream.",
          links: [],
        },
        {
          id: "bench", name: "Manual TIG benches",
          see: "Welders at benches under magnification, with foot pedals, argon trailing shields and purge chambers for titanium. Weld colour tells the story: silver or straw passes, blue or grey is rejected.",
          people: ["Certified welder: fine control and comfort over long shifts", "Welding engineer: procedures and qualifications"],
          pains: ["Qualified welder shortage", "Colour rejects on titanium", "Long qualification time for new welders"],
          products: ["Precision TIG power sources (AC/DC, pulse)", "Torches, tungsten, gas lenses", "Titanium and nickel filler rods"],
          ask: ["What is your weld-colour reject rate?", "How long does it take to qualify a new welder?"],
          play: "Premium TIG inverters with fine low-amp control and good torch ergonomics. Early involvement in qualifications matters.",
          links: ["proc_gtaw", "fil_tig", "fil_ni"],
        },
        {
          id: "auto", name: "Automated TIG & plasma cell",
          see: "A robot or CNC-controlled TIG or plasma torch welds rings and ducts on a rotating positioner with arc voltage control, logging every parameter. Orbital heads weld hydraulic and fuel tubes.",
          people: ["Cell operator", "Manufacturing engineer"],
          pains: ["Fixture accuracy", "Program qualification"],
          products: ["Automated TIG and plasma systems", "Orbital welding systems", "Weld monitoring"],
          ask: ["Which welds are you trying to take off the manual benches?"],
          play: "Automation plus data logging answers both the welder shortage and traceability requirements.",
          links: ["proc_paw", "auto_orbtube", "ndt_monitor"],
        },
        {
          id: "eb", name: "Electron beam & laser welding",
          see: "A large vacuum chamber for electron beam welding makes deep, narrow welds on rotating parts. Laser cells handle thin sections.",
          people: ["EB operator", "Process engineer"],
          pains: ["Pump-down time", "Joint fit-up"],
          products: ["Specialist beam-welding OEMs (not arc welding brands)"],
          ask: ["Which parts moved from TIG to EB or laser, and why?"],
          play: "Know the boundary: this is not arc welding territory. Watch which applications migrate here.",
          links: ["proc_laser"],
        },
        {
          id: "ht", name: "Heat treatment",
          see: "Vacuum furnaces stress-relieve and age-harden welded parts under controlled temperature records.",
          people: ["Heat-treat technician"],
          pains: ["Furnace capacity", "Distortion"],
          products: [],
          ask: ["Does distortion after heat treatment cause rework?"],
          play: "Context stop.",
          links: [],
        },
        {
          id: "ndt", name: "NDT: penetrant, X-ray, eddy current",
          see: "A fluorescent penetrant line with UV inspection booths, an X-ray / CT vault behind thick walls, and eddy-current benches. Level 3 inspectors sign off each part.",
          people: ["NDT Level 2/3 inspectors", "Quality manager"],
          pains: ["Inspection capacity", "False calls and escapes"],
          products: ["NDT systems and services"],
          ask: ["Which weld defects do you find most?"],
          play: "Defect data links back to welding parameters and consumable cleanliness.",
          links: ["ndt_pt", "ndt_rt", "ndt_et"],
        },
        {
          id: "records", name: "Records & certification",
          see: "Traveller paperwork, weld logs and qualification records, ready for Nadcap and customer audits.",
          people: ["Quality engineer", "Auditor"],
          pains: ["Paperwork burden", "Audit findings"],
          products: ["Weld data and traceability software"],
          ask: ["How are weld parameters recorded today?"],
          play: "Digital weld records cut audit effort. Traceability is a buying reason in aerospace.",
          links: ["ndt_monitor"],
        },
      ],
    },

    /* ========================== SHIPYARD ========================== */
    {
      id: "ship", name: "Shipyard", segment: "seg_ship", apps: ["app_panel", "app_erection", "app_offjacket"], tier: "Heavy",
      sum: "A shipyard is a series of factories feeding a dock. Steel is cut and joined into flat panels, panels become 3D blocks, blocks are outfitted and painted, then lifted by a giant crane and welded together in the dock.",
      facts: [
        ["Steel", "Tens of thousands of tonnes a year at a large yard (indicative)"],
        ["Workforce", "Thousands of people, many subcontracted"],
        ["Main processes", "Rutile flux-cored everywhere; one-sided SAW and tandem MIG on panel lines; electrogas on vertical erection seams"],
        ["Key metric", "Man-hours per compensated gross tonne (CGT)"],
        ["Rules", "Class societies (ABS, DNV, LR); NAVSEA for naval work"],
      ],
      economics: "Labor hours dominate. Every hour moved from the dock into the panel line or block hall is cheaper, safer and better: welding flat in a hall instead of overhead in a dock.",
      before: "Yard orientation and confined-space rules. Hi-vis. Watch for heavy transporters and cranes.",
      stops: [
        {
          id: "stock", name: "Steel stockyard & cutting",
          see: "Plates are shot-blasted and primed, then plasma-cut and marked on large CNC tables. Profiles for stiffeners are cut on separate lines.",
          people: ["Cutting operator", "Material planner"],
          pains: ["Plate logistics", "Primer affects welding later (porosity)"],
          products: ["Plasma cutting systems and consumables"],
          ask: ["Which shop primer, and at what thickness?"],
          play: "Cutting systems plus weldability-friendly primers and wires make one joined-up conversation.",
          links: [],
        },
        {
          id: "panel", name: "Panel line",
          see: "Plates are butt-welded into large flat panels by one-sided SAW on a flux-copper backing. A gantry then fillet-welds stiffeners (longitudinals) with several MIG or flux-cored torches at once.",
          people: ["Line operator", "Line manager: panels per shift"],
          pains: ["Line stoppages", "Distortion of thin panels", "Porosity from primer"],
          products: ["SAW heads, flux and wire", "Multi-torch gantries", "Metal-cored and flux-cored wire that tolerates primer"],
          ask: ["How many panels per shift?", "Do you see porosity from primer on the fillets?"],
          play: "A whole-line package: SAW, gantry torches, wire and flux, with a productivity guarantee.",
          links: ["app_panel", "auto_gantry", "proc_saw"],
        },
        {
          id: "block", name: "Block assembly hall",
          see: "Web frames and brackets are welded into 3D blocks. Dozens of welders work inside compartments with rutile flux-cored wire and portable feeders, while rail carriages run long fillets. Fume extraction hoses snake through openings.",
          people: ["Welders, often subcontracted", "Block supervisor", "Safety officer"],
          pains: ["Fume in enclosed spaces", "Low arc-on time", "Distortion"],
          products: ["Rutile FCAW-G wire (E71T-1)", "Portable feeders", "Welding carriages (e.g. Railtrac, Miggytrac)", "Ceramic backing", "Fume extraction"],
          ask: ["How many welders per block, and which wire?", "Where could carriages replace manual fillets?"],
          play: "Rutile flux-cored is the yard's highest-volume consumable. Carriages raise arc-on time and make a clear productivity story.",
          links: ["app_erection", "fil_fcawg", "auto_tractor"],
        },
        {
          id: "outfit", name: "Outfitting & paint",
          see: "Blocks get pipes, foundations and brackets (MIG and TIG), then go into paint halls before erection.",
          people: ["Outfitters", "Paint supervisors"],
          pains: ["Welding after paint damages the coating"],
          products: ["MIG and TIG for outfitting"],
          ask: ["How much welding happens after painting?"],
          play: "Pre-outfitting more work in the block is cheaper. Support it with productive, portable equipment.",
          links: [],
        },
        {
          id: "dock", name: "Dry dock erection",
          see: "A goliath crane lifts blocks of hundreds of tonnes into the dock. Erection seams are welded vertically, horizontally and overhead from staging: electrogas on long verticals and flux-cored with carriages elsewhere.",
          people: ["Erection welders", "Crane team", "Hull supervisor"],
          pains: ["Out-of-position welding", "Weather and cold", "Crane time", "Confined spaces"],
          products: ["Electrogas machines", "FCAW-G wire and ceramic backing", "Carriages and portable feeders"],
          ask: ["What limits erection speed: crane, fit-up or welding?"],
          play: "Out-of-position productivity (electrogas, carriages, all-position wire) is where the yard spends the most hours.",
          links: ["app_erection", "proc_esw"],
        },
        {
          id: "qa", name: "Class inspection & UT",
          see: "Class surveyors and yard QA check butt welds with UT and RT, and compartments with tightness tests.",
          people: ["Class surveyor (ABS, DNV, LR)", "Yard QA"],
          pains: ["Repairs found late in the dock", "Survey scheduling"],
          products: ["UT and RT", "Approved consumables list"],
          ask: ["Which consumables are class-approved here?"],
          play: "Class approval of consumables is the entry ticket. Make sure the product range carries the right approvals.",
          links: ["ndt_ut", "ndt_rt"],
        },
      ],
    },
  ],
};
